// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCleaner creates a new instance of MockCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleaner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCleaner is an autogenerated mock type for the Cleaner type
type MockCleaner struct {
	mock.Mock
}

type MockCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleaner) EXPECT() *MockCleaner_Expecter {
	return &MockCleaner_Expecter{mock: &_m.Mock}
}

// CleanupAll provides a mock function for the type MockCleaner
func (_mock *MockCleaner) CleanupAll(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCleaner_CleanupAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupAll'
type MockCleaner_CleanupAll_Call struct {
	*mock.Call
}

// CleanupAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCleaner_Expecter) CleanupAll(ctx any) *MockCleaner_CleanupAll_Call {
	return &MockCleaner_CleanupAll_Call{Call: _e.mock.On("CleanupAll", ctx)}
}

func (_c *MockCleaner_CleanupAll_Call) Run(run func(ctx context.Context)) *MockCleaner_CleanupAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCleaner_CleanupAll_Call) Return(err error) *MockCleaner_CleanupAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCleaner_CleanupAll_Call) RunAndReturn(run func(ctx context.Context) error) *MockCleaner_CleanupAll_Call {
	_c.Call.Return(run)
	return _c
}
