// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCleaner is an autogenerated mock type for the Cleaner type
type MockCleaner struct {
	mock.Mock
}

type MockCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleaner) EXPECT() *MockCleaner_Expecter {
	return &MockCleaner_Expecter{mock: &_m.Mock}
}

// CleanupAll provides a mock function with given fields: ctx
func (_m *MockCleaner) CleanupAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleaner_CleanupAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupAll'
type MockCleaner_CleanupAll_Call struct {
	*mock.Call
}

// CleanupAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCleaner_Expecter) CleanupAll(ctx interface{}) *MockCleaner_CleanupAll_Call {
	return &MockCleaner_CleanupAll_Call{Call: _e.mock.On("CleanupAll", ctx)}
}

func (_c *MockCleaner_CleanupAll_Call) Run(run func(ctx context.Context)) *MockCleaner_CleanupAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCleaner_CleanupAll_Call) Return(_a0 error) *MockCleaner_CleanupAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleaner_CleanupAll_Call) RunAndReturn(run func(context.Context) error) *MockCleaner_CleanupAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCleaner creates a new instance of MockCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleaner {
	mock := &MockCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
