// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMigration creates a new instance of MockMigration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigration {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMigration{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMigration is an autogenerated mock type for the Migration type
type MockMigration struct {
	mock.Mock
}

type MockMigration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigration) EXPECT() *MockMigration_Expecter {
	return &MockMigration_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type MockMigration
func (_mock *MockMigration) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMigration_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockMigration_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockMigration_Expecter) Description() *MockMigration_Description_Call {
	return &MockMigration_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockMigration_Description_Call) Run(run func()) *MockMigration_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigration_Description_Call) Return(s string) *MockMigration_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMigration_Description_Call) RunAndReturn(run func() string) *MockMigration_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Down provides a mock function for the type MockMigration
func (_mock *MockMigration) Down(ctx context.Context, tx *sql.Tx) error {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx) error); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigration_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MockMigration_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
func (_e *MockMigration_Expecter) Down(ctx any, tx any) *MockMigration_Down_Call {
	return &MockMigration_Down_Call{Call: _e.mock.On("Down", ctx, tx)}
}

func (_c *MockMigration_Down_Call) Run(run func(ctx context.Context, tx *sql.Tx)) *MockMigration_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigration_Down_Call) Return(err error) *MockMigration_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigration_Down_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx) error) *MockMigration_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockMigration
func (_mock *MockMigration) Up(ctx context.Context, tx *sql.Tx) error {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx) error); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigration_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockMigration_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
func (_e *MockMigration_Expecter) Up(ctx any, tx any) *MockMigration_Up_Call {
	return &MockMigration_Up_Call{Call: _e.mock.On("Up", ctx, tx)}
}

func (_c *MockMigration_Up_Call) Run(run func(ctx context.Context, tx *sql.Tx)) *MockMigration_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigration_Up_Call) Return(err error) *MockMigration_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigration_Up_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx) error) *MockMigration_Up_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockMigration
func (_mock *MockMigration) Version() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockMigration_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockMigration_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockMigration_Expecter) Version() *MockMigration_Version_Call {
	return &MockMigration_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockMigration_Version_Call) Run(run func()) *MockMigration_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigration_Version_Call) Return(n int) *MockMigration_Version_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMigration_Version_Call) RunAndReturn(run func() int) *MockMigration_Version_Call {
	_c.Call.Return(run)
	return _c
}
