// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/dombyte/solis/internal/util"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// NewTicker provides a mock function for the type MockClock
func (_mock *MockClock) NewTicker(d time.Duration) util.Ticker {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for NewTicker")
	}

	var r0 util.Ticker
	if returnFunc, ok := ret.Get(0).(func(time.Duration) util.Ticker); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(util.Ticker)
		}
	}
	return r0
}

// MockClock_NewTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTicker'
type MockClock_NewTicker_Call struct {
	*mock.Call
}

// NewTicker is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockClock_Expecter) NewTicker(d any) *MockClock_NewTicker_Call {
	return &MockClock_NewTicker_Call{Call: _e.mock.On("NewTicker", d)}
}

func (_c *MockClock_NewTicker_Call) Run(run func(d time.Duration)) *MockClock_NewTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_NewTicker_Call) Return(ticker util.Ticker) *MockClock_NewTicker_Call {
	_c.Call.Return(ticker)
	return _c
}

func (_c *MockClock_NewTicker_Call) RunAndReturn(run func(d time.Duration) util.Ticker) *MockClock_NewTicker_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimer provides a mock function for the type MockClock
func (_mock *MockClock) NewTimer(d time.Duration) util.Timer {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for NewTimer")
	}

	var r0 util.Timer
	if returnFunc, ok := ret.Get(0).(func(time.Duration) util.Timer); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(util.Timer)
		}
	}
	return r0
}

// MockClock_NewTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTimer'
type MockClock_NewTimer_Call struct {
	*mock.Call
}

// NewTimer is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockClock_Expecter) NewTimer(d any) *MockClock_NewTimer_Call {
	return &MockClock_NewTimer_Call{Call: _e.mock.On("NewTimer", d)}
}

func (_c *MockClock_NewTimer_Call) Run(run func(d time.Duration)) *MockClock_NewTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_NewTimer_Call) Return(timer util.Timer) *MockClock_NewTimer_Call {
	_c.Call.Return(timer)
	return _c
}

func (_c *MockClock_NewTimer_Call) RunAndReturn(run func(d time.Duration) util.Timer) *MockClock_NewTimer_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}
