// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTimer creates a new instance of MockTimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTimer is an autogenerated mock type for the Timer type
type MockTimer struct {
	mock.Mock
}

type MockTimer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimer) EXPECT() *MockTimer_Expecter {
	return &MockTimer_Expecter{mock: &_m.Mock}
}

// C provides a mock function for the type MockTimer
func (_mock *MockTimer) C() <-chan time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for C")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// MockTimer_C_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'C'
type MockTimer_C_Call struct {
	*mock.Call
}

// C is a helper method to define mock.On call
func (_e *MockTimer_Expecter) C() *MockTimer_C_Call {
	return &MockTimer_C_Call{Call: _e.mock.On("C")}
}

func (_c *MockTimer_C_Call) Run(run func()) *MockTimer_C_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTimer_C_Call) Return(timeCh <-chan time.Time) *MockTimer_C_Call {
	_c.Call.Return(timeCh)
	return _c
}

func (_c *MockTimer_C_Call) RunAndReturn(run func() <-chan time.Time) *MockTimer_C_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockTimer
func (_mock *MockTimer) Reset(d time.Duration) bool {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(time.Duration) bool); ok {
		r0 = returnFunc(d)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTimer_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockTimer_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockTimer_Expecter) Reset(d any) *MockTimer_Reset_Call {
	return &MockTimer_Reset_Call{Call: _e.mock.On("Reset", d)}
}

func (_c *MockTimer_Reset_Call) Run(run func(d time.Duration)) *MockTimer_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTimer_Reset_Call) Return(b bool) *MockTimer_Reset_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTimer_Reset_Call) RunAndReturn(run func(d time.Duration) bool) *MockTimer_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockTimer
func (_mock *MockTimer) Stop() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTimer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTimer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockTimer_Expecter) Stop() *MockTimer_Stop_Call {
	return &MockTimer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockTimer_Stop_Call) Run(run func()) *MockTimer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTimer_Stop_Call) Return(b bool) *MockTimer_Stop_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTimer_Stop_Call) RunAndReturn(run func() bool) *MockTimer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
