// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeySet creates a new instance of MockKeySet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeySet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeySet {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockKeySet{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockKeySet is an autogenerated mock type for the KeySet type
type MockKeySet struct {
	mock.Mock
}

type MockKeySet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeySet) EXPECT() *MockKeySet_Expecter {
	return &MockKeySet_Expecter{mock: &_m.Mock}
}

// ByKey provides a mock function for the type MockKeySet
func (_mock *MockKeySet) ByKey(key string) (solis.Register, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockKeySet_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockKeySet_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockKeySet_Expecter) ByKey(key any) *MockKeySet_ByKey_Call {
	return &MockKeySet_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockKeySet_ByKey_Call) Run(run func(key string)) *MockKeySet_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeySet_ByKey_Call) Return(register solis.Register, b bool) *MockKeySet_ByKey_Call {
	_c.Call.Return(register, b)
	return _c
}

func (_c *MockKeySet_ByKey_Call) RunAndReturn(run func(key string) (solis.Register, bool)) *MockKeySet_ByKey_Call {
	_c.Call.Return(run)
	return _c
}
