// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	solis "github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// MockSnapshotter is an autogenerated mock type for the Snapshotter type
type MockSnapshotter struct {
	mock.Mock
}

type MockSnapshotter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotter) EXPECT() *MockSnapshotter_Expecter {
	return &MockSnapshotter_Expecter{mock: &_m.Mock}
}

// GetMultiple provides a mock function with given fields: keys
func (_m *MockSnapshotter) GetMultiple(keys []string) map[string]*solis.Value {
	ret := _m.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for GetMultiple")
	}

	var r0 map[string]*solis.Value
	if rf, ok := ret.Get(0).(func([]string) map[string]*solis.Value); ok {
		r0 = rf(keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*solis.Value)
		}
	}

	return r0
}

// MockSnapshotter_GetMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultiple'
type MockSnapshotter_GetMultiple_Call struct {
	*mock.Call
}

// GetMultiple is a helper method to define mock.On call
//   - keys []string
func (_e *MockSnapshotter_Expecter) GetMultiple(keys interface{}) *MockSnapshotter_GetMultiple_Call {
	return &MockSnapshotter_GetMultiple_Call{Call: _e.mock.On("GetMultiple", keys)}
}

func (_c *MockSnapshotter_GetMultiple_Call) Run(run func(keys []string)) *MockSnapshotter_GetMultiple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockSnapshotter_GetMultiple_Call) Return(_a0 map[string]*solis.Value) *MockSnapshotter_GetMultiple_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSnapshotter_GetMultiple_Call) RunAndReturn(run func([]string) map[string]*solis.Value) *MockSnapshotter_GetMultiple_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnapshotter creates a new instance of MockSnapshotter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotter {
	mock := &MockSnapshotter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
