// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/websocket"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHubSource creates a new instance of MockHubSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHubSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHubSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHubSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHubSource is an autogenerated mock type for the HubSource type
type MockHubSource struct {
	mock.Mock
}

type MockHubSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHubSource) EXPECT() *MockHubSource_Expecter {
	return &MockHubSource_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockHubSource
func (_mock *MockHubSource) Load() (*websocket.Hub, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *websocket.Hub
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (*websocket.Hub, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *websocket.Hub); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.Hub)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHubSource_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockHubSource_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockHubSource_Expecter) Load() *MockHubSource_Load_Call {
	return &MockHubSource_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockHubSource_Load_Call) Run(run func()) *MockHubSource_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHubSource_Load_Call) Return(hub *websocket.Hub, b bool) *MockHubSource_Load_Call {
	_c.Call.Return(hub, b)
	return _c
}

func (_c *MockHubSource_Load_Call) RunAndReturn(run func() (*websocket.Hub, bool)) *MockHubSource_Load_Call {
	_c.Call.Return(run)
	return _c
}
