// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	health "github.com/dombyte/solis/internal/health"
	mock "github.com/stretchr/testify/mock"
)

// MockHealthSnapshotter is an autogenerated mock type for the HealthSnapshotter type
type MockHealthSnapshotter struct {
	mock.Mock
}

type MockHealthSnapshotter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthSnapshotter) EXPECT() *MockHealthSnapshotter_Expecter {
	return &MockHealthSnapshotter_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function with no fields
func (_m *MockHealthSnapshotter) Snapshot() health.Snapshot {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 health.Snapshot
	if rf, ok := ret.Get(0).(func() health.Snapshot); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(health.Snapshot)
	}

	return r0
}

// MockHealthSnapshotter_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockHealthSnapshotter_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockHealthSnapshotter_Expecter) Snapshot() *MockHealthSnapshotter_Snapshot_Call {
	return &MockHealthSnapshotter_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockHealthSnapshotter_Snapshot_Call) Run(run func()) *MockHealthSnapshotter_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthSnapshotter_Snapshot_Call) Return(_a0 health.Snapshot) *MockHealthSnapshotter_Snapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthSnapshotter_Snapshot_Call) RunAndReturn(run func() health.Snapshot) *MockHealthSnapshotter_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthSnapshotter creates a new instance of MockHealthSnapshotter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthSnapshotter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthSnapshotter {
	mock := &MockHealthSnapshotter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
