// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusDecoder creates a new instance of MockStatusDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusDecoder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStatusDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStatusDecoder is an autogenerated mock type for the StatusDecoder type
type MockStatusDecoder struct {
	mock.Mock
}

type MockStatusDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusDecoder) EXPECT() *MockStatusDecoder_Expecter {
	return &MockStatusDecoder_Expecter{mock: &_m.Mock}
}

// DecodeStatus provides a mock function for the type MockStatusDecoder
func (_mock *MockStatusDecoder) DecodeStatus(key string, raw uint16) any {
	ret := _mock.Called(key, raw)

	if len(ret) == 0 {
		panic("no return value specified for DecodeStatus")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(string, uint16) any); ok {
		r0 = returnFunc(key, raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockStatusDecoder_DecodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeStatus'
type MockStatusDecoder_DecodeStatus_Call struct {
	*mock.Call
}

// DecodeStatus is a helper method to define mock.On call
//   - key string
//   - raw uint16
func (_e *MockStatusDecoder_Expecter) DecodeStatus(key any, raw any) *MockStatusDecoder_DecodeStatus_Call {
	return &MockStatusDecoder_DecodeStatus_Call{Call: _e.mock.On("DecodeStatus", key, raw)}
}

func (_c *MockStatusDecoder_DecodeStatus_Call) Run(run func(key string, raw uint16)) *MockStatusDecoder_DecodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatusDecoder_DecodeStatus_Call) Return(anyMoqParam any) *MockStatusDecoder_DecodeStatus_Call {
	_c.Call.Return(anyMoqParam)
	return _c
}

func (_c *MockStatusDecoder_DecodeStatus_Call) RunAndReturn(run func(key string, raw uint16) any) *MockStatusDecoder_DecodeStatus_Call {
	_c.Call.Return(run)
	return _c
}
