// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	solis "github.com/dombyte/solis/internal/solis"
)

// MockCacheReader is an autogenerated mock type for the CacheReader type
type MockCacheReader struct {
	mock.Mock
}

type MockCacheReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheReader) EXPECT() *MockCacheReader_Expecter {
	return &MockCacheReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockCacheReader) Get(key string) *solis.Value {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *solis.Value
	if rf, ok := ret.Get(0).(func(string) *solis.Value); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*solis.Value)
		}
	}

	return r0
}

// MockCacheReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockCacheReader_Expecter) Get(key interface{}) *MockCacheReader_Get_Call {
	return &MockCacheReader_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCacheReader_Get_Call) Run(run func(key string)) *MockCacheReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCacheReader_Get_Call) Return(_a0 *solis.Value) *MockCacheReader_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheReader_Get_Call) RunAndReturn(run func(string) *solis.Value) *MockCacheReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheReader creates a new instance of MockCacheReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheReader {
	mock := &MockCacheReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
