// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStatusDecoder is an autogenerated mock type for the StatusDecoder type
type MockStatusDecoder struct {
	mock.Mock
}

type MockStatusDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusDecoder) EXPECT() *MockStatusDecoder_Expecter {
	return &MockStatusDecoder_Expecter{mock: &_m.Mock}
}

// DecodeStatus provides a mock function with given fields: key, raw
func (_m *MockStatusDecoder) DecodeStatus(key string, raw uint16) any {
	ret := _m.Called(key, raw)

	if len(ret) == 0 {
		panic("no return value specified for DecodeStatus")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func(string, uint16) any); ok {
		r0 = rf(key, raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// MockStatusDecoder_DecodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeStatus'
type MockStatusDecoder_DecodeStatus_Call struct {
	*mock.Call
}

// DecodeStatus is a helper method to define mock.On call
//   - key string
//   - raw uint16
func (_e *MockStatusDecoder_Expecter) DecodeStatus(key interface{}, raw interface{}) *MockStatusDecoder_DecodeStatus_Call {
	return &MockStatusDecoder_DecodeStatus_Call{Call: _e.mock.On("DecodeStatus", key, raw)}
}

func (_c *MockStatusDecoder_DecodeStatus_Call) Run(run func(key string, raw uint16)) *MockStatusDecoder_DecodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint16))
	})
	return _c
}

func (_c *MockStatusDecoder_DecodeStatus_Call) Return(_a0 any) *MockStatusDecoder_DecodeStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatusDecoder_DecodeStatus_Call) RunAndReturn(run func(string, uint16) any) *MockStatusDecoder_DecodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatusDecoder creates a new instance of MockStatusDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusDecoder {
	mock := &MockStatusDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
