// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	solis "github.com/dombyte/solis/internal/solis"
)

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// All provides a mock function with no fields
func (_m *MockRegistry) All() []solis.Register {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []solis.Register
	if rf, ok := ret.Get(0).(func() []solis.Register); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Register)
		}
	}

	return r0
}

// MockRegistry_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockRegistry_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) All() *MockRegistry_All_Call {
	return &MockRegistry_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockRegistry_All_Call) Run(run func()) *MockRegistry_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_All_Call) Return(_a0 []solis.Register) *MockRegistry_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_All_Call) RunAndReturn(run func() []solis.Register) *MockRegistry_All_Call {
	_c.Call.Return(run)
	return _c
}

// ByKey provides a mock function with given fields: key
func (_m *MockRegistry) ByKey(key string) (solis.Register, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockRegistry_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockRegistry_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockRegistry_Expecter) ByKey(key interface{}) *MockRegistry_ByKey_Call {
	return &MockRegistry_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockRegistry_ByKey_Call) Run(run func(key string)) *MockRegistry_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_ByKey_Call) Return(_a0 solis.Register, _a1 bool) *MockRegistry_ByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistry_ByKey_Call) RunAndReturn(run func(string) (solis.Register, bool)) *MockRegistry_ByKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
