// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// ReplaceDomain provides a mock function for the type MockCache
func (_mock *MockCache) ReplaceDomain(domain string, values map[string]*solis.Value, at time.Time) {
	_mock.Called(domain, values, at)
	return
}

// MockCache_ReplaceDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceDomain'
type MockCache_ReplaceDomain_Call struct {
	*mock.Call
}

// ReplaceDomain is a helper method to define mock.On call
//   - domain string
//   - values map[string]*solis.Value
//   - at time.Time
func (_e *MockCache_Expecter) ReplaceDomain(domain any, values any, at any) *MockCache_ReplaceDomain_Call {
	return &MockCache_ReplaceDomain_Call{Call: _e.mock.On("ReplaceDomain", domain, values, at)}
}

func (_c *MockCache_ReplaceDomain_Call) Run(run func(domain string, values map[string]*solis.Value, at time.Time)) *MockCache_ReplaceDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]*solis.Value
		if args[1] != nil {
			arg1 = args[1].(map[string]*solis.Value)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_ReplaceDomain_Call) Return() *MockCache_ReplaceDomain_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_ReplaceDomain_Call) RunAndReturn(run func(domain string, values map[string]*solis.Value, at time.Time)) *MockCache_ReplaceDomain_Call {
	_c.Run(run)
	return _c
}
