// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Blocks provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Blocks() []solis.Block {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Blocks")
	}

	var r0 []solis.Block
	if returnFunc, ok := ret.Get(0).(func() []solis.Block); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Block)
		}
	}
	return r0
}

// MockRegistry_Blocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Blocks'
type MockRegistry_Blocks_Call struct {
	*mock.Call
}

// Blocks is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) Blocks() *MockRegistry_Blocks_Call {
	return &MockRegistry_Blocks_Call{Call: _e.mock.On("Blocks")}
}

func (_c *MockRegistry_Blocks_Call) Run(run func()) *MockRegistry_Blocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_Blocks_Call) Return(blocks []solis.Block) *MockRegistry_Blocks_Call {
	_c.Call.Return(blocks)
	return _c
}

func (_c *MockRegistry_Blocks_Call) RunAndReturn(run func() []solis.Block) *MockRegistry_Blocks_Call {
	_c.Call.Return(run)
	return _c
}

// ByKey provides a mock function for the type MockRegistry
func (_mock *MockRegistry) ByKey(key string) (solis.Register, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRegistry_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockRegistry_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockRegistry_Expecter) ByKey(key any) *MockRegistry_ByKey_Call {
	return &MockRegistry_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockRegistry_ByKey_Call) Run(run func(key string)) *MockRegistry_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_ByKey_Call) Return(register solis.Register, b bool) *MockRegistry_ByKey_Call {
	_c.Call.Return(register, b)
	return _c
}

func (_c *MockRegistry_ByKey_Call) RunAndReturn(run func(key string) (solis.Register, bool)) *MockRegistry_ByKey_Call {
	_c.Call.Return(run)
	return _c
}

// DailyKeys provides a mock function for the type MockRegistry
func (_mock *MockRegistry) DailyKeys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DailyKeys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockRegistry_DailyKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DailyKeys'
type MockRegistry_DailyKeys_Call struct {
	*mock.Call
}

// DailyKeys is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) DailyKeys() *MockRegistry_DailyKeys_Call {
	return &MockRegistry_DailyKeys_Call{Call: _e.mock.On("DailyKeys")}
}

func (_c *MockRegistry_DailyKeys_Call) Run(run func()) *MockRegistry_DailyKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_DailyKeys_Call) Return(strings []string) *MockRegistry_DailyKeys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockRegistry_DailyKeys_Call) RunAndReturn(run func() []string) *MockRegistry_DailyKeys_Call {
	_c.Call.Return(run)
	return _c
}
