// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	solis "github.com/dombyte/solis/internal/solis"

	time "time"
)

// MockDecoder is an autogenerated mock type for the Decoder type
type MockDecoder struct {
	mock.Mock
}

type MockDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecoder) EXPECT() *MockDecoder_Expecter {
	return &MockDecoder_Expecter{mock: &_m.Mock}
}

// DecodeBlock provides a mock function with given fields: b, raw, at
func (_m *MockDecoder) DecodeBlock(b solis.Block, raw []uint16, at time.Time) map[string]*solis.Value {
	ret := _m.Called(b, raw, at)

	if len(ret) == 0 {
		panic("no return value specified for DecodeBlock")
	}

	var r0 map[string]*solis.Value
	if rf, ok := ret.Get(0).(func(solis.Block, []uint16, time.Time) map[string]*solis.Value); ok {
		r0 = rf(b, raw, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*solis.Value)
		}
	}

	return r0
}

// MockDecoder_DecodeBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeBlock'
type MockDecoder_DecodeBlock_Call struct {
	*mock.Call
}

// DecodeBlock is a helper method to define mock.On call
//   - b solis.Block
//   - raw []uint16
//   - at time.Time
func (_e *MockDecoder_Expecter) DecodeBlock(b interface{}, raw interface{}, at interface{}) *MockDecoder_DecodeBlock_Call {
	return &MockDecoder_DecodeBlock_Call{Call: _e.mock.On("DecodeBlock", b, raw, at)}
}

func (_c *MockDecoder_DecodeBlock_Call) Run(run func(b solis.Block, raw []uint16, at time.Time)) *MockDecoder_DecodeBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(solis.Block), args[1].([]uint16), args[2].(time.Time))
	})
	return _c
}

func (_c *MockDecoder_DecodeBlock_Call) Return(_a0 map[string]*solis.Value) *MockDecoder_DecodeBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDecoder_DecodeBlock_Call) RunAndReturn(run func(solis.Block, []uint16, time.Time) map[string]*solis.Value) *MockDecoder_DecodeBlock_Call {
	_c.Call.Return(run)
	return _c
}

// Derive provides a mock function with given fields: values, at
func (_m *MockDecoder) Derive(values map[string]*solis.Value, at time.Time) {
	_m.Called(values, at)
}

// MockDecoder_Derive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Derive'
type MockDecoder_Derive_Call struct {
	*mock.Call
}

// Derive is a helper method to define mock.On call
//   - values map[string]*solis.Value
//   - at time.Time
func (_e *MockDecoder_Expecter) Derive(values interface{}, at interface{}) *MockDecoder_Derive_Call {
	return &MockDecoder_Derive_Call{Call: _e.mock.On("Derive", values, at)}
}

func (_c *MockDecoder_Derive_Call) Run(run func(values map[string]*solis.Value, at time.Time)) *MockDecoder_Derive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]*solis.Value), args[1].(time.Time))
	})
	return _c
}

func (_c *MockDecoder_Derive_Call) Return() *MockDecoder_Derive_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDecoder_Derive_Call) RunAndReturn(run func(map[string]*solis.Value, time.Time)) *MockDecoder_Derive_Call {
	_c.Run(run)
	return _c
}

// NewMockDecoder creates a new instance of MockDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecoder {
	mock := &MockDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
