// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDecoder creates a new instance of MockDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecoder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDecoder is an autogenerated mock type for the Decoder type
type MockDecoder struct {
	mock.Mock
}

type MockDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecoder) EXPECT() *MockDecoder_Expecter {
	return &MockDecoder_Expecter{mock: &_m.Mock}
}

// DecodeBlock provides a mock function for the type MockDecoder
func (_mock *MockDecoder) DecodeBlock(b solis.Block, raw []uint16, at time.Time) map[string]*solis.Value {
	ret := _mock.Called(b, raw, at)

	if len(ret) == 0 {
		panic("no return value specified for DecodeBlock")
	}

	var r0 map[string]*solis.Value
	if returnFunc, ok := ret.Get(0).(func(solis.Block, []uint16, time.Time) map[string]*solis.Value); ok {
		r0 = returnFunc(b, raw, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*solis.Value)
		}
	}
	return r0
}

// MockDecoder_DecodeBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeBlock'
type MockDecoder_DecodeBlock_Call struct {
	*mock.Call
}

// DecodeBlock is a helper method to define mock.On call
//   - b solis.Block
//   - raw []uint16
//   - at time.Time
func (_e *MockDecoder_Expecter) DecodeBlock(b any, raw any, at any) *MockDecoder_DecodeBlock_Call {
	return &MockDecoder_DecodeBlock_Call{Call: _e.mock.On("DecodeBlock", b, raw, at)}
}

func (_c *MockDecoder_DecodeBlock_Call) Run(run func(b solis.Block, raw []uint16, at time.Time)) *MockDecoder_DecodeBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 solis.Block
		if args[0] != nil {
			arg0 = args[0].(solis.Block)
		}
		var arg1 []uint16
		if args[1] != nil {
			arg1 = args[1].([]uint16)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDecoder_DecodeBlock_Call) Return(stringToValue map[string]*solis.Value) *MockDecoder_DecodeBlock_Call {
	_c.Call.Return(stringToValue)
	return _c
}

func (_c *MockDecoder_DecodeBlock_Call) RunAndReturn(run func(b solis.Block, raw []uint16, at time.Time) map[string]*solis.Value) *MockDecoder_DecodeBlock_Call {
	_c.Call.Return(run)
	return _c
}

// Derive provides a mock function for the type MockDecoder
func (_mock *MockDecoder) Derive(values map[string]*solis.Value, at time.Time) {
	_mock.Called(values, at)
	return
}

// MockDecoder_Derive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Derive'
type MockDecoder_Derive_Call struct {
	*mock.Call
}

// Derive is a helper method to define mock.On call
//   - values map[string]*solis.Value
//   - at time.Time
func (_e *MockDecoder_Expecter) Derive(values any, at any) *MockDecoder_Derive_Call {
	return &MockDecoder_Derive_Call{Call: _e.mock.On("Derive", values, at)}
}

func (_c *MockDecoder_Derive_Call) Run(run func(values map[string]*solis.Value, at time.Time)) *MockDecoder_Derive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]*solis.Value
		if args[0] != nil {
			arg0 = args[0].(map[string]*solis.Value)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDecoder_Derive_Call) Return() *MockDecoder_Derive_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDecoder_Derive_Call) RunAndReturn(run func(values map[string]*solis.Value, at time.Time)) *MockDecoder_Derive_Call {
	_c.Run(run)
	return _c
}
