// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// IsConnected provides a mock function for the type MockReader
func (_mock *MockReader) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockReader_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockReader_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockReader_Expecter) IsConnected() *MockReader_IsConnected_Call {
	return &MockReader_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockReader_IsConnected_Call) Run(run func()) *MockReader_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_IsConnected_Call) Return(b bool) *MockReader_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockReader_IsConnected_Call) RunAndReturn(run func() bool) *MockReader_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRegisters provides a mock function for the type MockReader
func (_mock *MockReader) ReadRegisters(ctx context.Context, addr uint16, count uint16) ([]uint16, error) {
	ret := _mock.Called(ctx, addr, count)

	if len(ret) == 0 {
		panic("no return value specified for ReadRegisters")
	}

	var r0 []uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, uint16) ([]uint16, error)); ok {
		return returnFunc(ctx, addr, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, uint16) []uint16); ok {
		r0 = returnFunc(ctx, addr, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, addr, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_ReadRegisters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRegisters'
type MockReader_ReadRegisters_Call struct {
	*mock.Call
}

// ReadRegisters is a helper method to define mock.On call
//   - ctx context.Context
//   - addr uint16
//   - count uint16
func (_e *MockReader_Expecter) ReadRegisters(ctx any, addr any, count any) *MockReader_ReadRegisters_Call {
	return &MockReader_ReadRegisters_Call{Call: _e.mock.On("ReadRegisters", ctx, addr, count)}
}

func (_c *MockReader_ReadRegisters_Call) Run(run func(ctx context.Context, addr uint16, count uint16)) *MockReader_ReadRegisters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReader_ReadRegisters_Call) Return(uint16s []uint16, err error) *MockReader_ReadRegisters_Call {
	_c.Call.Return(uint16s, err)
	return _c
}

func (_c *MockReader_ReadRegisters_Call) RunAndReturn(run func(ctx context.Context, addr uint16, count uint16) ([]uint16, error)) *MockReader_ReadRegisters_Call {
	_c.Call.Return(run)
	return _c
}
