// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	poller "github.com/dombyte/solis/internal/poller"
)

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockSource) Load() (poller.Reader, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 poller.Reader
	var r1 bool
	if rf, ok := ret.Get(0).(func() (poller.Reader, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() poller.Reader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(poller.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockSource_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSource_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockSource_Expecter) Load() *MockSource_Load_Call {
	return &MockSource_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockSource_Load_Call) Run(run func()) *MockSource_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Load_Call) Return(_a0 poller.Reader, _a1 bool) *MockSource_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_Load_Call) RunAndReturn(run func() (poller.Reader, bool)) *MockSource_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
