// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// IsConnected provides a mock function with no fields
func (_m *MockReader) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockReader_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockReader_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockReader_Expecter) IsConnected() *MockReader_IsConnected_Call {
	return &MockReader_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockReader_IsConnected_Call) Run(run func()) *MockReader_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_IsConnected_Call) Return(_a0 bool) *MockReader_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReader_IsConnected_Call) RunAndReturn(run func() bool) *MockReader_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRegisters provides a mock function with given fields: ctx, addr, count
func (_m *MockReader) ReadRegisters(ctx context.Context, addr uint16, count uint16) ([]uint16, error) {
	ret := _m.Called(ctx, addr, count)

	if len(ret) == 0 {
		panic("no return value specified for ReadRegisters")
	}

	var r0 []uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint16, uint16) ([]uint16, error)); ok {
		return rf(ctx, addr, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint16, uint16) []uint16); ok {
		r0 = rf(ctx, addr, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint16, uint16) error); ok {
		r1 = rf(ctx, addr, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_ReadRegisters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRegisters'
type MockReader_ReadRegisters_Call struct {
	*mock.Call
}

// ReadRegisters is a helper method to define mock.On call
//   - ctx context.Context
//   - addr uint16
//   - count uint16
func (_e *MockReader_Expecter) ReadRegisters(ctx interface{}, addr interface{}, count interface{}) *MockReader_ReadRegisters_Call {
	return &MockReader_ReadRegisters_Call{Call: _e.mock.On("ReadRegisters", ctx, addr, count)}
}

func (_c *MockReader_ReadRegisters_Call) Run(run func(ctx context.Context, addr uint16, count uint16)) *MockReader_ReadRegisters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint16), args[2].(uint16))
	})
	return _c
}

func (_c *MockReader_ReadRegisters_Call) Return(_a0 []uint16, _a1 error) *MockReader_ReadRegisters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_ReadRegisters_Call) RunAndReturn(run func(context.Context, uint16, uint16) ([]uint16, error)) *MockReader_ReadRegisters_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
