// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	solis "github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Merge provides a mock function with given fields: domain, values, at
func (_m *MockCache) Merge(domain string, values map[string]*solis.Value, at time.Time) {
	_m.Called(domain, values, at)
}

// MockCache_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockCache_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - domain string
//   - values map[string]*solis.Value
//   - at time.Time
func (_e *MockCache_Expecter) Merge(domain interface{}, values interface{}, at interface{}) *MockCache_Merge_Call {
	return &MockCache_Merge_Call{Call: _e.mock.On("Merge", domain, values, at)}
}

func (_c *MockCache_Merge_Call) Run(run func(domain string, values map[string]*solis.Value, at time.Time)) *MockCache_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]*solis.Value), args[2].(time.Time))
	})
	return _c
}

func (_c *MockCache_Merge_Call) Return() *MockCache_Merge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Merge_Call) RunAndReturn(run func(string, map[string]*solis.Value, time.Time)) *MockCache_Merge_Call {
	_c.Run(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
