// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dombyte/solis/internal/health"
	"github.com/dombyte/solis/internal/service"
	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadService creates a new instance of MockReadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReadService is an autogenerated mock type for the ReadService type
type MockReadService struct {
	mock.Mock
}

type MockReadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadService) EXPECT() *MockReadService_Expecter {
	return &MockReadService_Expecter{mock: &_m.Mock}
}

// Data provides a mock function for the type MockReadService
func (_mock *MockReadService) Data(ctx context.Context, q service.DataQuery) (service.DataResult, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 service.DataResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.DataQuery) (service.DataResult, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.DataQuery) service.DataResult); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(service.DataResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.DataQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadService_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockReadService_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - ctx context.Context
//   - q service.DataQuery
func (_e *MockReadService_Expecter) Data(ctx any, q any) *MockReadService_Data_Call {
	return &MockReadService_Data_Call{Call: _e.mock.On("Data", ctx, q)}
}

func (_c *MockReadService_Data_Call) Run(run func(ctx context.Context, q service.DataQuery)) *MockReadService_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.DataQuery
		if args[1] != nil {
			arg1 = args[1].(service.DataQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadService_Data_Call) Return(dataResult service.DataResult, err error) *MockReadService_Data_Call {
	_c.Call.Return(dataResult, err)
	return _c
}

func (_c *MockReadService_Data_Call) RunAndReturn(run func(ctx context.Context, q service.DataQuery) (service.DataResult, error)) *MockReadService_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockReadService
func (_mock *MockReadService) Health() health.Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 health.Snapshot
	if returnFunc, ok := ret.Get(0).(func() health.Snapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(health.Snapshot)
	}
	return r0
}

// MockReadService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockReadService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockReadService_Expecter) Health() *MockReadService_Health_Call {
	return &MockReadService_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockReadService_Health_Call) Run(run func()) *MockReadService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadService_Health_Call) Return(snapshot health.Snapshot) *MockReadService_Health_Call {
	_c.Call.Return(snapshot)
	return _c
}

func (_c *MockReadService_Health_Call) RunAndReturn(run func() health.Snapshot) *MockReadService_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockReadService
func (_mock *MockReadService) Keys() []solis.Register {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []solis.Register
	if returnFunc, ok := ret.Get(0).(func() []solis.Register); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Register)
		}
	}
	return r0
}

// MockReadService_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockReadService_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockReadService_Expecter) Keys() *MockReadService_Keys_Call {
	return &MockReadService_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockReadService_Keys_Call) Run(run func()) *MockReadService_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadService_Keys_Call) Return(registers []solis.Register) *MockReadService_Keys_Call {
	_c.Call.Return(registers)
	return _c
}

func (_c *MockReadService_Keys_Call) RunAndReturn(run func() []solis.Register) *MockReadService_Keys_Call {
	_c.Call.Return(run)
	return _c
}
