// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	solis "github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// MockLookup is an autogenerated mock type for the Lookup type
type MockLookup struct {
	mock.Mock
}

type MockLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLookup) EXPECT() *MockLookup_Expecter {
	return &MockLookup_Expecter{mock: &_m.Mock}
}

// ByAddress provides a mock function with given fields: addr
func (_m *MockLookup) ByAddress(addr uint16) (solis.Register, bool) {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for ByAddress")
	}

	var r0 solis.Register
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint16) (solis.Register, bool)); ok {
		return rf(addr)
	}
	if rf, ok := ret.Get(0).(func(uint16) solis.Register); ok {
		r0 = rf(addr)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}

	if rf, ok := ret.Get(1).(func(uint16) bool); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockLookup_ByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByAddress'
type MockLookup_ByAddress_Call struct {
	*mock.Call
}

// ByAddress is a helper method to define mock.On call
//   - addr uint16
func (_e *MockLookup_Expecter) ByAddress(addr interface{}) *MockLookup_ByAddress_Call {
	return &MockLookup_ByAddress_Call{Call: _e.mock.On("ByAddress", addr)}
}

func (_c *MockLookup_ByAddress_Call) Run(run func(addr uint16)) *MockLookup_ByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16))
	})
	return _c
}

func (_c *MockLookup_ByAddress_Call) Return(_a0 solis.Register, _a1 bool) *MockLookup_ByAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLookup_ByAddress_Call) RunAndReturn(run func(uint16) (solis.Register, bool)) *MockLookup_ByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ByKey provides a mock function with given fields: key
func (_m *MockLookup) ByKey(key string) (solis.Register, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockLookup_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockLookup_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockLookup_Expecter) ByKey(key interface{}) *MockLookup_ByKey_Call {
	return &MockLookup_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockLookup_ByKey_Call) Run(run func(key string)) *MockLookup_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLookup_ByKey_Call) Return(_a0 solis.Register, _a1 bool) *MockLookup_ByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLookup_ByKey_Call) RunAndReturn(run func(string) (solis.Register, bool)) *MockLookup_ByKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLookup creates a new instance of MockLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLookup {
	mock := &MockLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
