// Register configuration
// Static configuration for all displayed registers with custom labels and endpoints

// Endpoint types for each register
export type RegisterEndpoint =
  | "data" // /api/v1/data/{key} - real-time values
  | "status" // /api/v1/status/{key} - status/fault register values
  | "daily" // /api/v1/daily/{key} - daily values
  | "monthly" // /api/v1/monthly/{key} - monthly values
  | "yearly" // /api/v1/yearly/{key} - yearly values
  | "total"; // /api/v1/total/{key} - lifetime/total values

// Configuration for a single register
export interface RegisterConfig {
  key: string;
  name: string; // Custom display name (not from API)
  endpoint: RegisterEndpoint;
  unit?: string; // Optional: override unit from API
  description?: string; // Optional: description for tooltip
}

// Configuration for a card/group of registers
export interface CardConfig {
  title: string;
  registers: RegisterConfig[];
}

// All configured registers with their display properties
export const registerConfigs: RegisterConfig[] = [
  // Power Card
  {
    key: "total_pv_power",
    name: "Total PV Power",
    endpoint: "data",
    unit: "W",
    description: "The total power currently being generated by all PV panels",
  },
  {
    key: "battery_soc",
    name: "Battery State of Charge",
    endpoint: "data",
    unit: "%",
    description:
      "The current charge level of the battery as a percentage of its total capacity",
  },
  {
    key: "battery_soh",
    name: "Battery State of Health",
    endpoint: "data",
    unit: "%",
    description:
      "The overall health of the battery as a percentage, indicating its capacity relative to when it was new",
  },
  {
    key: "battery_power",
    name: "Battery Power",
    endpoint: "data",
    unit: "W",
    description:
      "The current power being delivered (positive) or consumed (negative) by the battery",
  },
  {
    key: "active_power",
    name: "Active Power",
    endpoint: "data",
    unit: "W",
    description: "Solis Active Power",
  },
  {
    key: "household_load_power",
    name: "Household Load Power",
    endpoint: "data",
    unit: "W",
    description: "Solis Household Load Power",
  },
  {
    key: "backup_load_power",
    name: "Backup Load Power",
    endpoint: "data",
    unit: "W",
    description: "Solis Backup Load Power",
  },
  {
    key: "meter_total_active_power",
    name: "Meter Total Active Power",
    endpoint: "data",
    unit: "W",
    description: "Solis Meter Total Active Power",
  },

  // Energy Card
  {
    key: "pv_today_energy",
    name: "PV Energy Today",
    endpoint: "daily",
    unit: "kWh",
    description: "Total solar energy generated by PV panels today",
  },
  {
    key: "household_load_today_energy",
    name: "Household Load Energy Today",
    endpoint: "daily",
    unit: "kWh",
    description: "Total energy consumed by household loads today",
  },
  {
    key: "today_energy_consumption",
    name: "Today Energy Consumption",
    endpoint: "daily",
    unit: "kWh",
    description:
      "Total energy consumed by all loads including household and backup today",
  },
  {
    key: "today_energy_imported_from_grid",
    name: "Energy Imported from Grid",
    endpoint: "daily",
    unit: "kWh",
    description: "Total energy imported from the electrical grid today",
  },
  {
    key: "today_energy_fed_into_grid",
    name: "Energy Fed into Grid",
    endpoint: "daily",
    unit: "kWh",
    description: "Total excess energy fed back into the electrical grid today",
  },
  {
    key: "today_grid_energy",
    name: "Grid Energy (Net)",
    endpoint: "daily",
    unit: "kWh",
    description: "Net grid energy (export - import): positive = net export to grid, negative = net import from grid. NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "today_battery_discharge_energy",
    name: "Battery Discharge Energy Today",
    endpoint: "daily",
    unit: "kWh",
    description: "Total energy discharged from the battery today",
  },
  {
    key: "today_battery_charge_energy",
    name: "Battery Charge Energy Today",
    endpoint: "daily",
    unit: "kWh",
    description: "Total energy used to charge the battery today",
  },
  {
    key: "backup_load_today_energy",
    name: "Backup Load Energy Today",
    endpoint: "daily",
    unit: "kWh",
    description: "Total energy consumed by backup loads today",
  },
  // Monthly Energy Registers
  {
    key: "pv_month_energy",
    name: "PV Energy This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total solar energy generated by PV panels this month",
  },
  {
    key: "household_load_month_energy",
    name: "Household Load Energy This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy consumed by household loads this month",
  },
  {
    key: "backup_load_month_energy",
    name: "Backup Load Energy This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy consumed by backup loads this month",
  },
  // Yearly Energy Registers
  {
    key: "pv_year_energy",
    name: "PV Energy This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total solar energy generated by PV panels this year",
  },
  {
    key: "household_load_year_energy",
    name: "Household Load Energy This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy consumed by household loads this year",
  },
  {
    key: "backup_load_year_energy",
    name: "Backup Load Energy This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy consumed by backup loads this year",
  },
  // Computed Monthly Energy Registers
  {
    key: "energy_consumption_month_energy",
    name: "Energy Consumption This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy consumed by all loads this month (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "energy_fed_into_grid_month_energy",
    name: "Energy Fed into Grid This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy fed back into the grid this month (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "energy_imported_from_grid_month_energy",
    name: "Energy Imported from Grid This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy imported from the grid this month (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "battery_discharge_month_energy",
    name: "Battery Discharge Energy This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy discharged from battery this month (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "battery_charge_month_energy",
    name: "Battery Charge Energy This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Total energy used to charge battery this month (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "month_grid_energy",
    name: "Grid Energy (Net) This Month",
    endpoint: "monthly",
    unit: "kWh",
    description: "Net grid energy this month (export - import, computed). NOTE: This is a computed value and may be inaccurate.",
  },
  // Computed Yearly Energy Registers
  {
    key: "energy_consumption_year_energy",
    name: "Energy Consumption This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy consumed by all loads this year (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "energy_fed_into_grid_year_energy",
    name: "Energy Fed into Grid This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy fed back into the grid this year (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "energy_imported_from_grid_year_energy",
    name: "Energy Imported from Grid This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy imported from the grid this year (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "battery_discharge_year_energy",
    name: "Battery Discharge Energy This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy discharged from battery this year (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "battery_charge_year_energy",
    name: "Battery Charge Energy This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Total energy used to charge battery this year (computed from daily values). NOTE: This is a computed value and may be inaccurate.",
  },
  {
    key: "year_grid_energy",
    name: "Grid Energy (Net) This Year",
    endpoint: "yearly",
    unit: "kWh",
    description: "Net grid energy this year (export - import, computed). NOTE: This is a computed value and may be inaccurate.",
  },
  // Total Energy Registers
  {
    key: "pv_total_energy",
    name: "Total PV Energy",
    endpoint: "total",
    unit: "kWh",
    description: "Total solar energy generated by PV panels since installation",
  },
  {
    key: "household_load_total_energy",
    name: "Total Household Load Energy",
    endpoint: "total",
    unit: "kWh",
    description: "Total energy consumed by household loads since installation",
  },
  {
    key: "backup_load_total_energy",
    name: "Total Backup Load Energy",
    endpoint: "total",
    unit: "kWh",
    description: "Total energy consumed by backup loads since installation",
  },
  {
    key: "total_energy_imported_from_grid",
    name: "Total Energy Imported from Grid",
    endpoint: "total",
    unit: "kWh",
    description:
      "Total energy imported from the electrical grid since installation",
  },
  {
    key: "total_energy_fed_into_grid",
    name: "Total Energy Fed into Grid",
    endpoint: "total",
    unit: "kWh",
    description:
      "Total excess energy fed back into the electrical grid since installation",
  },
  {
    key: "total_grid_energy",
    name: "Total Grid Energy (Net)",
    endpoint: "total",
    unit: "kWh",
    description:
      "Net grid energy (export - import): positive = net export to grid, negative = net import from grid. NOTE: This is a computed value and may be inaccurate.",
  },
  // Status Registers
  {
    key: "temperature",
    name: "Temperature",
    endpoint: "data",
    unit: "°C",
    description: "Solis inverter temperature",
  },
  {
    key: "solis_status",
    name: "Solis Status",
    endpoint: "status",
    description: "Overall system status from Solis inverter",
  },
  {
    key: "operating_status",
    name: "Operating Status",
    endpoint: "status",
    description: "Current operating state of the inverter",
  },
  {
    key: "grid_fault_status_01",
    name: "Grid Fault Status",
    endpoint: "status",
    description: "Fault status related to grid connection",
  },
  {
    key: "battery_fault_status_1_bms",
    name: "Battery 1 BMS Fault Status",
    endpoint: "status",
    description: "Fault status for Battery 1 BMS",
  },
  {
    key: "battery_fault_status_2_bms",
    name: "Battery 2 BMS Fault Status",
    endpoint: "status",
    description: "Fault status for Battery 2 BMS",
  },
  {
    key: "backup_load_fault_status_02",
    name: "Backup Load Fault Status",
    endpoint: "status",
    description: "Fault status related to backup load",
  },
  {
    key: "battery_fault_status_03",
    name: "Battery Fault Status 03",
    endpoint: "status",
    description: "Battery fault status register 03",
  },
  {
    key: "device_fault_status_04",
    name: "Device Fault Status 04",
    endpoint: "status",
    description: "Device fault status register 04",
  },
  {
    key: "device_fault_status_05",
    name: "Device Fault Status 05",
    endpoint: "status",
    description: "Device fault status register 05",
  },
];

// Card configuration - which registers go in which card
export const cards: CardConfig[] = [
  {
    title: "Status",
    registers: [
      {
        key: "temperature",
        name: "Temperature",
        endpoint: "data",
        unit: "°C",
      },
      {
        key: "solis_status",
        name: "Solis Status",
        endpoint: "status",
      },
      {
        key: "operating_status",
        name: "Operating Status",
        endpoint: "status",
      },
      {
        key: "grid_fault_status_01",
        name: "Grid Fault Status",
        endpoint: "status",
      },
      {
        key: "battery_fault_status_1_bms",
        name: "Battery 1 BMS Fault Status",
        endpoint: "status",
      },
      {
        key: "battery_fault_status_2_bms",
        name: "Battery 2 BMS Fault Status",
        endpoint: "status",
      },
      {
        key: "backup_load_fault_status_02",
        name: "Backup Load Fault Status",
        endpoint: "status",
      },
      {
        key: "battery_fault_status_03",
        name: "Battery Fault Status 03",
        endpoint: "status",
      },
      {
        key: "device_fault_status_04",
        name: "Device Fault Status 04",
        endpoint: "status",
      },
      {
        key: "device_fault_status_05",
        name: "Device Fault Status 05",
        endpoint: "status",
      },
    ],
  },
  {
    title: "Power & Battery",
    registers: [
      {
        key: "total_pv_power",
        name: "PV Power",
        endpoint: "data",
        unit: "W",
      },
      {
        key: "active_power",
        name: "Active Power",
        endpoint: "data",
        unit: "W",
      },
      {
        key: "household_load_power",
        name: "Household Load Power",
        endpoint: "data",
        unit: "W",
      },
      {
        key: "backup_load_power",
        name: "Backup Load Power",
        endpoint: "data",
        unit: "W",
      },
      {
        key: "meter_total_active_power",
        name: "Meter Total Active Power",
        endpoint: "data",
        unit: "W",
      },
      {
        key: "battery_soc",
        name: "Battery State of Charge",
        endpoint: "data",
        unit: "%",
      },
      {
        key: "battery_soh",
        name: "Battery State of Health",
        endpoint: "data",
        unit: "%",
      },
      {
        key: "battery_power",
        name: "Battery Power",
        endpoint: "data",
        unit: "W",
      },
    ],
  },
  {
    title: "Today's Energy",
    registers: [
      {
        key: "pv_today_energy",
        name: "PV Energy Today",
        endpoint: "daily",
        unit: "kWh",
      },
      {
        key: "today_energy_imported_from_grid",
        name: "Energy Imported from Grid",
        endpoint: "daily",
        unit: "kWh",
      },
      {
        key: "today_energy_fed_into_grid",
        name: "Energy Fed into Grid",
        endpoint: "daily",
        unit: "kWh",
      },
      {
        key: "today_grid_energy",
        name: "Grid Energy (Net)",
        endpoint: "daily",
        unit: "kWh",
      },
    ],
  },
  {
    title: "This Month's Energy",
    registers: [
      {
        key: "pv_month_energy",
        name: "PV Energy This Month",
        endpoint: "monthly",
        unit: "kWh",
      },
      {
        key: "household_load_month_energy",
        name: "Household Load Energy This Month",
        endpoint: "monthly",
        unit: "kWh",
      },
      {
        key: "backup_load_month_energy",
        name: "Backup Load Energy This Month",
        endpoint: "monthly",
        unit: "kWh",
      },
    ],
  },
  {
    title: "This Year's Energy",
    registers: [
      {
        key: "pv_year_energy",
        name: "PV Energy This Year",
        endpoint: "yearly",
        unit: "kWh",
      },
      {
        key: "household_load_year_energy",
        name: "Household Load Energy This Year",
        endpoint: "yearly",
        unit: "kWh",
      },
      {
        key: "backup_load_year_energy",
        name: "Backup Load Energy This Year",
        endpoint: "yearly",
        unit: "kWh",
      },
    ],
  },
  {
    title: "Total Energy",
    registers: [
      {
        key: "pv_total_energy",
        name: "Total PV Energy",
        endpoint: "total",
        unit: "kWh",
      },
      {
        key: "household_load_total_energy",
        name: "Total Household Load Energy",
        endpoint: "total",
        unit: "kWh",
      },
      {
        key: "backup_load_total_energy",
        name: "Total Backup Load Energy",
        endpoint: "total",
        unit: "kWh",
      },
      {
        key: "total_energy_imported_from_grid",
        name: "Total Energy Imported from Grid",
        endpoint: "total",
        unit: "kWh",
      },
      {
        key: "total_energy_fed_into_grid",
        name: "Total Energy Fed into Grid",
        endpoint: "total",
        unit: "kWh",
      },
      {
        key: "total_grid_energy",
        name: "Total Grid Energy (Net)",
        endpoint: "total",
        unit: "kWh",
      },
    ],
  },
];

// Get endpoint for a specific key
export function getEndpoint(key: string): RegisterConfig | null {
  return registerConfigs.find((c) => c.key === key) || null;
}

// Check if a key is configured
export function isConfigured(key: string): boolean {
  return registerConfigs.some((c) => c.key === key);
}

// Get all configured keys
export function getAllConfiguredKeys(): string[] {
  return registerConfigs.map((c) => c.key);
}

// Get register config by key
export function getRegisterConfig(key: string): RegisterConfig | null {
  return registerConfigs.find((c) => c.key === key) || null;
}
