// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/period"
	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// ByKey provides a mock function for the type MockRegistry
func (_mock *MockRegistry) ByKey(key string) (solis.Register, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRegistry_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockRegistry_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockRegistry_Expecter) ByKey(key any) *MockRegistry_ByKey_Call {
	return &MockRegistry_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockRegistry_ByKey_Call) Run(run func(key string)) *MockRegistry_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_ByKey_Call) Return(register solis.Register, b bool) *MockRegistry_ByKey_Call {
	_c.Call.Return(register, b)
	return _c
}

func (_c *MockRegistry_ByKey_Call) RunAndReturn(run func(key string) (solis.Register, bool)) *MockRegistry_ByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Edges provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Edges(l period.Level) []solis.Edge {
	ret := _mock.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for Edges")
	}

	var r0 []solis.Edge
	if returnFunc, ok := ret.Get(0).(func(period.Level) []solis.Edge); ok {
		r0 = returnFunc(l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Edge)
		}
	}
	return r0
}

// MockRegistry_Edges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edges'
type MockRegistry_Edges_Call struct {
	*mock.Call
}

// Edges is a helper method to define mock.On call
//   - l period.Level
func (_e *MockRegistry_Expecter) Edges(l any) *MockRegistry_Edges_Call {
	return &MockRegistry_Edges_Call{Call: _e.mock.On("Edges", l)}
}

func (_c *MockRegistry_Edges_Call) Run(run func(l period.Level)) *MockRegistry_Edges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 period.Level
		if args[0] != nil {
			arg0 = args[0].(period.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Edges_Call) Return(edges []solis.Edge) *MockRegistry_Edges_Call {
	_c.Call.Return(edges)
	return _c
}

func (_c *MockRegistry_Edges_Call) RunAndReturn(run func(l period.Level) []solis.Edge) *MockRegistry_Edges_Call {
	_c.Call.Return(run)
	return _c
}

// NetPairs provides a mock function for the type MockRegistry
func (_mock *MockRegistry) NetPairs(l period.Level) []solis.NetPair {
	ret := _mock.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for NetPairs")
	}

	var r0 []solis.NetPair
	if returnFunc, ok := ret.Get(0).(func(period.Level) []solis.NetPair); ok {
		r0 = returnFunc(l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.NetPair)
		}
	}
	return r0
}

// MockRegistry_NetPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetPairs'
type MockRegistry_NetPairs_Call struct {
	*mock.Call
}

// NetPairs is a helper method to define mock.On call
//   - l period.Level
func (_e *MockRegistry_Expecter) NetPairs(l any) *MockRegistry_NetPairs_Call {
	return &MockRegistry_NetPairs_Call{Call: _e.mock.On("NetPairs", l)}
}

func (_c *MockRegistry_NetPairs_Call) Run(run func(l period.Level)) *MockRegistry_NetPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 period.Level
		if args[0] != nil {
			arg0 = args[0].(period.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_NetPairs_Call) Return(netPairs []solis.NetPair) *MockRegistry_NetPairs_Call {
	_c.Call.Return(netPairs)
	return _c
}

func (_c *MockRegistry_NetPairs_Call) RunAndReturn(run func(l period.Level) []solis.NetPair) *MockRegistry_NetPairs_Call {
	_c.Call.Return(run)
	return _c
}
