// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dombyte/solis/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Backfill provides a mock function for the type MockStore
func (_mock *MockStore) Backfill(ctx context.Context, fn func(storage.BackfillTx) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Backfill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(storage.BackfillTx) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Backfill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backfill'
type MockStore_Backfill_Call struct {
	*mock.Call
}

// Backfill is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(storage.BackfillTx) error
func (_e *MockStore_Expecter) Backfill(ctx any, fn any) *MockStore_Backfill_Call {
	return &MockStore_Backfill_Call{Call: _e.mock.On("Backfill", ctx, fn)}
}

func (_c *MockStore_Backfill_Call) Run(run func(ctx context.Context, fn func(storage.BackfillTx) error)) *MockStore_Backfill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(storage.BackfillTx) error
		if args[1] != nil {
			arg1 = args[1].(func(storage.BackfillTx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Backfill_Call) Return(err error) *MockStore_Backfill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Backfill_Call) RunAndReturn(run func(ctx context.Context, fn func(storage.BackfillTx) error) error) *MockStore_Backfill_Call {
	_c.Call.Return(run)
	return _c
}
