// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/health"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// Report provides a mock function for the type MockReporter
func (_mock *MockReporter) Report(s health.State, reason string) {
	_mock.Called(s, reason)
	return
}

// MockReporter_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockReporter_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - s health.State
//   - reason string
func (_e *MockReporter_Expecter) Report(s any, reason any) *MockReporter_Report_Call {
	return &MockReporter_Report_Call{Call: _e.mock.On("Report", s, reason)}
}

func (_c *MockReporter_Report_Call) Run(run func(s health.State, reason string)) *MockReporter_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 health.State
		if args[0] != nil {
			arg0 = args[0].(health.State)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReporter_Report_Call) Return() *MockReporter_Report_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Report_Call) RunAndReturn(run func(s health.State, reason string)) *MockReporter_Report_Call {
	_c.Run(run)
	return _c
}
