// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dombyte/solis/internal/health"
	mock "github.com/stretchr/testify/mock"
)

// NewMockComponent creates a new instance of MockComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponent {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockComponent is an autogenerated mock type for the Component type
type MockComponent struct {
	mock.Mock
}

type MockComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponent) EXPECT() *MockComponent_Expecter {
	return &MockComponent_Expecter{mock: &_m.Mock}
}

// LastBeat provides a mock function for the type MockComponent
func (_mock *MockComponent) LastBeat() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastBeat")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockComponent_LastBeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastBeat'
type MockComponent_LastBeat_Call struct {
	*mock.Call
}

// LastBeat is a helper method to define mock.On call
func (_e *MockComponent_Expecter) LastBeat() *MockComponent_LastBeat_Call {
	return &MockComponent_LastBeat_Call{Call: _e.mock.On("LastBeat")}
}

func (_c *MockComponent_LastBeat_Call) Run(run func()) *MockComponent_LastBeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_LastBeat_Call) Return(time1 time.Time) *MockComponent_LastBeat_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockComponent_LastBeat_Call) RunAndReturn(run func() time.Time) *MockComponent_LastBeat_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockComponent
func (_mock *MockComponent) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComponent_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockComponent_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockComponent_Expecter) Start(ctx any) *MockComponent_Start_Call {
	return &MockComponent_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockComponent_Start_Call) Run(run func(ctx context.Context)) *MockComponent_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockComponent_Start_Call) Return(err error) *MockComponent_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComponent_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockComponent_Start_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type MockComponent
func (_mock *MockComponent) State() health.State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 health.State
	if returnFunc, ok := ret.Get(0).(func() health.State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(health.State)
	}
	return r0
}

// MockComponent_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockComponent_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockComponent_Expecter) State() *MockComponent_State_Call {
	return &MockComponent_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockComponent_State_Call) Run(run func()) *MockComponent_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_State_Call) Return(state health.State) *MockComponent_State_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockComponent_State_Call) RunAndReturn(run func() health.State) *MockComponent_State_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockComponent
func (_mock *MockComponent) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComponent_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockComponent_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Stop() *MockComponent_Stop_Call {
	return &MockComponent_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockComponent_Stop_Call) Run(run func()) *MockComponent_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Stop_Call) Return(err error) *MockComponent_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComponent_Stop_Call) RunAndReturn(run func() error) *MockComponent_Stop_Call {
	_c.Call.Return(run)
	return _c
}
