// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	health "github.com/dombyte/solis/internal/health"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockComponent is an autogenerated mock type for the Component type
type MockComponent struct {
	mock.Mock
}

type MockComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponent) EXPECT() *MockComponent_Expecter {
	return &MockComponent_Expecter{mock: &_m.Mock}
}

// LastBeat provides a mock function with no fields
func (_m *MockComponent) LastBeat() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastBeat")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockComponent_LastBeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastBeat'
type MockComponent_LastBeat_Call struct {
	*mock.Call
}

// LastBeat is a helper method to define mock.On call
func (_e *MockComponent_Expecter) LastBeat() *MockComponent_LastBeat_Call {
	return &MockComponent_LastBeat_Call{Call: _e.mock.On("LastBeat")}
}

func (_c *MockComponent_LastBeat_Call) Run(run func()) *MockComponent_LastBeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_LastBeat_Call) Return(_a0 time.Time) *MockComponent_LastBeat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_LastBeat_Call) RunAndReturn(run func() time.Time) *MockComponent_LastBeat_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockComponent) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponent_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockComponent_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockComponent_Expecter) Start(ctx interface{}) *MockComponent_Start_Call {
	return &MockComponent_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockComponent_Start_Call) Run(run func(ctx context.Context)) *MockComponent_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockComponent_Start_Call) Return(_a0 error) *MockComponent_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Start_Call) RunAndReturn(run func(context.Context) error) *MockComponent_Start_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockComponent) State() health.State {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 health.State
	if rf, ok := ret.Get(0).(func() health.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(health.State)
	}

	return r0
}

// MockComponent_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockComponent_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockComponent_Expecter) State() *MockComponent_State_Call {
	return &MockComponent_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockComponent_State_Call) Run(run func()) *MockComponent_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_State_Call) Return(_a0 health.State) *MockComponent_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_State_Call) RunAndReturn(run func() health.State) *MockComponent_State_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockComponent) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponent_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockComponent_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Stop() *MockComponent_Stop_Call {
	return &MockComponent_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockComponent_Stop_Call) Run(run func()) *MockComponent_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Stop_Call) Return(_a0 error) *MockComponent_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Stop_Call) RunAndReturn(run func() error) *MockComponent_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponent creates a new instance of MockComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponent {
	mock := &MockComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
