// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	health "github.com/dombyte/solis/internal/health"
	mock "github.com/stretchr/testify/mock"
)

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// Report provides a mock function with given fields: s, reason
func (_m *MockReporter) Report(s health.State, reason string) {
	_m.Called(s, reason)
}

// MockReporter_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockReporter_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - s health.State
//   - reason string
func (_e *MockReporter_Expecter) Report(s interface{}, reason interface{}) *MockReporter_Report_Call {
	return &MockReporter_Report_Call{Call: _e.mock.On("Report", s, reason)}
}

func (_c *MockReporter_Report_Call) Run(run func(s health.State, reason string)) *MockReporter_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(health.State), args[1].(string))
	})
	return _c
}

func (_c *MockReporter_Report_Call) Return() *MockReporter_Report_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Report_Call) RunAndReturn(run func(health.State, string)) *MockReporter_Report_Call {
	_c.Run(run)
	return _c
}

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
