// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/dombyte/solis/internal/history"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadStore creates a new instance of MockReadStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReadStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReadStore is an autogenerated mock type for the ReadStore type
type MockReadStore struct {
	mock.Mock
}

type MockReadStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadStore) EXPECT() *MockReadStore_Expecter {
	return &MockReadStore_Expecter{mock: &_m.Mock}
}

// GetDailyHistory provides a mock function for the type MockReadStore
func (_mock *MockReadStore) GetDailyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.DailyDataPoint, error) {
	ret := _mock.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyHistory")
	}

	var r0 []*history.DailyDataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.DailyDataPoint, error)); ok {
		return returnFunc(ctx, key, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.DailyDataPoint); ok {
		r0 = returnFunc(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.DailyDataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadStore_GetDailyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyHistory'
type MockReadStore_GetDailyHistory_Call struct {
	*mock.Call
}

// GetDailyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetDailyHistory(ctx any, key any, start any, end any) *MockReadStore_GetDailyHistory_Call {
	return &MockReadStore_GetDailyHistory_Call{Call: _e.mock.On("GetDailyHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetDailyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetDailyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReadStore_GetDailyHistory_Call) Return(dailyDataPoints []*history.DailyDataPoint, err error) *MockReadStore_GetDailyHistory_Call {
	_c.Call.Return(dailyDataPoints, err)
	return _c
}

func (_c *MockReadStore_GetDailyHistory_Call) RunAndReturn(run func(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.DailyDataPoint, error)) *MockReadStore_GetDailyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetErrorHistory provides a mock function for the type MockReadStore
func (_mock *MockReadStore) GetErrorHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.ErrorDataPoint, error) {
	ret := _mock.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetErrorHistory")
	}

	var r0 []*history.ErrorDataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.ErrorDataPoint, error)); ok {
		return returnFunc(ctx, key, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.ErrorDataPoint); ok {
		r0 = returnFunc(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.ErrorDataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadStore_GetErrorHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorHistory'
type MockReadStore_GetErrorHistory_Call struct {
	*mock.Call
}

// GetErrorHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetErrorHistory(ctx any, key any, start any, end any) *MockReadStore_GetErrorHistory_Call {
	return &MockReadStore_GetErrorHistory_Call{Call: _e.mock.On("GetErrorHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetErrorHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetErrorHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReadStore_GetErrorHistory_Call) Return(errorDataPoints []*history.ErrorDataPoint, err error) *MockReadStore_GetErrorHistory_Call {
	_c.Call.Return(errorDataPoints, err)
	return _c
}

func (_c *MockReadStore_GetErrorHistory_Call) RunAndReturn(run func(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.ErrorDataPoint, error)) *MockReadStore_GetErrorHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyHistory provides a mock function for the type MockReadStore
func (_mock *MockReadStore) GetMonthlyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.MonthlyDataPoint, error) {
	ret := _mock.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyHistory")
	}

	var r0 []*history.MonthlyDataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.MonthlyDataPoint, error)); ok {
		return returnFunc(ctx, key, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.MonthlyDataPoint); ok {
		r0 = returnFunc(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.MonthlyDataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadStore_GetMonthlyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyHistory'
type MockReadStore_GetMonthlyHistory_Call struct {
	*mock.Call
}

// GetMonthlyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetMonthlyHistory(ctx any, key any, start any, end any) *MockReadStore_GetMonthlyHistory_Call {
	return &MockReadStore_GetMonthlyHistory_Call{Call: _e.mock.On("GetMonthlyHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetMonthlyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetMonthlyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReadStore_GetMonthlyHistory_Call) Return(monthlyDataPoints []*history.MonthlyDataPoint, err error) *MockReadStore_GetMonthlyHistory_Call {
	_c.Call.Return(monthlyDataPoints, err)
	return _c
}

func (_c *MockReadStore_GetMonthlyHistory_Call) RunAndReturn(run func(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.MonthlyDataPoint, error)) *MockReadStore_GetMonthlyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalHistory provides a mock function for the type MockReadStore
func (_mock *MockReadStore) GetTotalHistory(ctx context.Context, key string) (*history.TotalDataPoint, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalHistory")
	}

	var r0 *history.TotalDataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*history.TotalDataPoint, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *history.TotalDataPoint); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.TotalDataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadStore_GetTotalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalHistory'
type MockReadStore_GetTotalHistory_Call struct {
	*mock.Call
}

// GetTotalHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReadStore_Expecter) GetTotalHistory(ctx any, key any) *MockReadStore_GetTotalHistory_Call {
	return &MockReadStore_GetTotalHistory_Call{Call: _e.mock.On("GetTotalHistory", ctx, key)}
}

func (_c *MockReadStore_GetTotalHistory_Call) Run(run func(ctx context.Context, key string)) *MockReadStore_GetTotalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadStore_GetTotalHistory_Call) Return(totalDataPoint *history.TotalDataPoint, err error) *MockReadStore_GetTotalHistory_Call {
	_c.Call.Return(totalDataPoint, err)
	return _c
}

func (_c *MockReadStore_GetTotalHistory_Call) RunAndReturn(run func(ctx context.Context, key string) (*history.TotalDataPoint, error)) *MockReadStore_GetTotalHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlyHistory provides a mock function for the type MockReadStore
func (_mock *MockReadStore) GetYearlyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.YearlyDataPoint, error) {
	ret := _mock.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlyHistory")
	}

	var r0 []*history.YearlyDataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.YearlyDataPoint, error)); ok {
		return returnFunc(ctx, key, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.YearlyDataPoint); ok {
		r0 = returnFunc(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.YearlyDataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadStore_GetYearlyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlyHistory'
type MockReadStore_GetYearlyHistory_Call struct {
	*mock.Call
}

// GetYearlyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetYearlyHistory(ctx any, key any, start any, end any) *MockReadStore_GetYearlyHistory_Call {
	return &MockReadStore_GetYearlyHistory_Call{Call: _e.mock.On("GetYearlyHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetYearlyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetYearlyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReadStore_GetYearlyHistory_Call) Return(yearlyDataPoints []*history.YearlyDataPoint, err error) *MockReadStore_GetYearlyHistory_Call {
	_c.Call.Return(yearlyDataPoints, err)
	return _c
}

func (_c *MockReadStore_GetYearlyHistory_Call) RunAndReturn(run func(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.YearlyDataPoint, error)) *MockReadStore_GetYearlyHistory_Call {
	_c.Call.Return(run)
	return _c
}
