// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	period "github.com/dombyte/solis/internal/period"
	mock "github.com/stretchr/testify/mock"

	solis "github.com/dombyte/solis/internal/solis"
)

// MockKeyLookup is an autogenerated mock type for the KeyLookup type
type MockKeyLookup struct {
	mock.Mock
}

type MockKeyLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyLookup) EXPECT() *MockKeyLookup_Expecter {
	return &MockKeyLookup_Expecter{mock: &_m.Mock}
}

// ByKey provides a mock function with given fields: key
func (_m *MockKeyLookup) ByKey(key string) (solis.Register, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockKeyLookup_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockKeyLookup_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockKeyLookup_Expecter) ByKey(key interface{}) *MockKeyLookup_ByKey_Call {
	return &MockKeyLookup_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockKeyLookup_ByKey_Call) Run(run func(key string)) *MockKeyLookup_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKeyLookup_ByKey_Call) Return(_a0 solis.Register, _a1 bool) *MockKeyLookup_ByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyLookup_ByKey_Call) RunAndReturn(run func(string) (solis.Register, bool)) *MockKeyLookup_ByKey_Call {
	_c.Call.Return(run)
	return _c
}

// DailyKeys provides a mock function with no fields
func (_m *MockKeyLookup) DailyKeys() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DailyKeys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockKeyLookup_DailyKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DailyKeys'
type MockKeyLookup_DailyKeys_Call struct {
	*mock.Call
}

// DailyKeys is a helper method to define mock.On call
func (_e *MockKeyLookup_Expecter) DailyKeys() *MockKeyLookup_DailyKeys_Call {
	return &MockKeyLookup_DailyKeys_Call{Call: _e.mock.On("DailyKeys")}
}

func (_c *MockKeyLookup_DailyKeys_Call) Run(run func()) *MockKeyLookup_DailyKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyLookup_DailyKeys_Call) Return(_a0 []string) *MockKeyLookup_DailyKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyLookup_DailyKeys_Call) RunAndReturn(run func() []string) *MockKeyLookup_DailyKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Edges provides a mock function with given fields: l
func (_m *MockKeyLookup) Edges(l period.Level) []solis.Edge {
	ret := _m.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for Edges")
	}

	var r0 []solis.Edge
	if rf, ok := ret.Get(0).(func(period.Level) []solis.Edge); ok {
		r0 = rf(l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Edge)
		}
	}

	return r0
}

// MockKeyLookup_Edges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edges'
type MockKeyLookup_Edges_Call struct {
	*mock.Call
}

// Edges is a helper method to define mock.On call
//   - l period.Level
func (_e *MockKeyLookup_Expecter) Edges(l interface{}) *MockKeyLookup_Edges_Call {
	return &MockKeyLookup_Edges_Call{Call: _e.mock.On("Edges", l)}
}

func (_c *MockKeyLookup_Edges_Call) Run(run func(l period.Level)) *MockKeyLookup_Edges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(period.Level))
	})
	return _c
}

func (_c *MockKeyLookup_Edges_Call) Return(_a0 []solis.Edge) *MockKeyLookup_Edges_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyLookup_Edges_Call) RunAndReturn(run func(period.Level) []solis.Edge) *MockKeyLookup_Edges_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyLookup creates a new instance of MockKeyLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyLookup {
	mock := &MockKeyLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
