// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/period"
	"github.com/dombyte/solis/internal/solis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyLookup creates a new instance of MockKeyLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyLookup {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockKeyLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockKeyLookup is an autogenerated mock type for the KeyLookup type
type MockKeyLookup struct {
	mock.Mock
}

type MockKeyLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyLookup) EXPECT() *MockKeyLookup_Expecter {
	return &MockKeyLookup_Expecter{mock: &_m.Mock}
}

// ByKey provides a mock function for the type MockKeyLookup
func (_mock *MockKeyLookup) ByKey(key string) (solis.Register, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ByKey")
	}

	var r0 solis.Register
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (solis.Register, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockKeyLookup_ByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByKey'
type MockKeyLookup_ByKey_Call struct {
	*mock.Call
}

// ByKey is a helper method to define mock.On call
//   - key string
func (_e *MockKeyLookup_Expecter) ByKey(key any) *MockKeyLookup_ByKey_Call {
	return &MockKeyLookup_ByKey_Call{Call: _e.mock.On("ByKey", key)}
}

func (_c *MockKeyLookup_ByKey_Call) Run(run func(key string)) *MockKeyLookup_ByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeyLookup_ByKey_Call) Return(register solis.Register, b bool) *MockKeyLookup_ByKey_Call {
	_c.Call.Return(register, b)
	return _c
}

func (_c *MockKeyLookup_ByKey_Call) RunAndReturn(run func(key string) (solis.Register, bool)) *MockKeyLookup_ByKey_Call {
	_c.Call.Return(run)
	return _c
}

// DailyKeys provides a mock function for the type MockKeyLookup
func (_mock *MockKeyLookup) DailyKeys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DailyKeys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockKeyLookup_DailyKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DailyKeys'
type MockKeyLookup_DailyKeys_Call struct {
	*mock.Call
}

// DailyKeys is a helper method to define mock.On call
func (_e *MockKeyLookup_Expecter) DailyKeys() *MockKeyLookup_DailyKeys_Call {
	return &MockKeyLookup_DailyKeys_Call{Call: _e.mock.On("DailyKeys")}
}

func (_c *MockKeyLookup_DailyKeys_Call) Run(run func()) *MockKeyLookup_DailyKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyLookup_DailyKeys_Call) Return(strings []string) *MockKeyLookup_DailyKeys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockKeyLookup_DailyKeys_Call) RunAndReturn(run func() []string) *MockKeyLookup_DailyKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Edges provides a mock function for the type MockKeyLookup
func (_mock *MockKeyLookup) Edges(l period.Level) []solis.Edge {
	ret := _mock.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for Edges")
	}

	var r0 []solis.Edge
	if returnFunc, ok := ret.Get(0).(func(period.Level) []solis.Edge); ok {
		r0 = returnFunc(l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Edge)
		}
	}
	return r0
}

// MockKeyLookup_Edges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edges'
type MockKeyLookup_Edges_Call struct {
	*mock.Call
}

// Edges is a helper method to define mock.On call
//   - l period.Level
func (_e *MockKeyLookup_Expecter) Edges(l any) *MockKeyLookup_Edges_Call {
	return &MockKeyLookup_Edges_Call{Call: _e.mock.On("Edges", l)}
}

func (_c *MockKeyLookup_Edges_Call) Run(run func(l period.Level)) *MockKeyLookup_Edges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 period.Level
		if args[0] != nil {
			arg0 = args[0].(period.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeyLookup_Edges_Call) Return(edges []solis.Edge) *MockKeyLookup_Edges_Call {
	_c.Call.Return(edges)
	return _c
}

func (_c *MockKeyLookup_Edges_Call) RunAndReturn(run func(l period.Level) []solis.Edge) *MockKeyLookup_Edges_Call {
	_c.Call.Return(run)
	return _c
}
