// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	history "github.com/dombyte/solis/internal/history"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockReadStore is an autogenerated mock type for the ReadStore type
type MockReadStore struct {
	mock.Mock
}

type MockReadStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadStore) EXPECT() *MockReadStore_Expecter {
	return &MockReadStore_Expecter{mock: &_m.Mock}
}

// GetDailyHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadStore) GetDailyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.DailyDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyHistory")
	}

	var r0 []*history.DailyDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.DailyDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.DailyDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.DailyDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadStore_GetDailyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyHistory'
type MockReadStore_GetDailyHistory_Call struct {
	*mock.Call
}

// GetDailyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetDailyHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadStore_GetDailyHistory_Call {
	return &MockReadStore_GetDailyHistory_Call{Call: _e.mock.On("GetDailyHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetDailyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetDailyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadStore_GetDailyHistory_Call) Return(_a0 []*history.DailyDataPoint, _a1 error) *MockReadStore_GetDailyHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadStore_GetDailyHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.DailyDataPoint, error)) *MockReadStore_GetDailyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetErrorHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadStore) GetErrorHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.ErrorDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetErrorHistory")
	}

	var r0 []*history.ErrorDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.ErrorDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.ErrorDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.ErrorDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadStore_GetErrorHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorHistory'
type MockReadStore_GetErrorHistory_Call struct {
	*mock.Call
}

// GetErrorHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetErrorHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadStore_GetErrorHistory_Call {
	return &MockReadStore_GetErrorHistory_Call{Call: _e.mock.On("GetErrorHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetErrorHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetErrorHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadStore_GetErrorHistory_Call) Return(_a0 []*history.ErrorDataPoint, _a1 error) *MockReadStore_GetErrorHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadStore_GetErrorHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.ErrorDataPoint, error)) *MockReadStore_GetErrorHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadStore) GetMonthlyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.MonthlyDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyHistory")
	}

	var r0 []*history.MonthlyDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.MonthlyDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.MonthlyDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.MonthlyDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadStore_GetMonthlyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyHistory'
type MockReadStore_GetMonthlyHistory_Call struct {
	*mock.Call
}

// GetMonthlyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetMonthlyHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadStore_GetMonthlyHistory_Call {
	return &MockReadStore_GetMonthlyHistory_Call{Call: _e.mock.On("GetMonthlyHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetMonthlyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetMonthlyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadStore_GetMonthlyHistory_Call) Return(_a0 []*history.MonthlyDataPoint, _a1 error) *MockReadStore_GetMonthlyHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadStore_GetMonthlyHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.MonthlyDataPoint, error)) *MockReadStore_GetMonthlyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalHistory provides a mock function with given fields: ctx, key
func (_m *MockReadStore) GetTotalHistory(ctx context.Context, key string) (*history.TotalDataPoint, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalHistory")
	}

	var r0 *history.TotalDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*history.TotalDataPoint, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *history.TotalDataPoint); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.TotalDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadStore_GetTotalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalHistory'
type MockReadStore_GetTotalHistory_Call struct {
	*mock.Call
}

// GetTotalHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReadStore_Expecter) GetTotalHistory(ctx interface{}, key interface{}) *MockReadStore_GetTotalHistory_Call {
	return &MockReadStore_GetTotalHistory_Call{Call: _e.mock.On("GetTotalHistory", ctx, key)}
}

func (_c *MockReadStore_GetTotalHistory_Call) Run(run func(ctx context.Context, key string)) *MockReadStore_GetTotalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReadStore_GetTotalHistory_Call) Return(_a0 *history.TotalDataPoint, _a1 error) *MockReadStore_GetTotalHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadStore_GetTotalHistory_Call) RunAndReturn(run func(context.Context, string) (*history.TotalDataPoint, error)) *MockReadStore_GetTotalHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlyHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadStore) GetYearlyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.YearlyDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlyHistory")
	}

	var r0 []*history.YearlyDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.YearlyDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.YearlyDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.YearlyDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadStore_GetYearlyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlyHistory'
type MockReadStore_GetYearlyHistory_Call struct {
	*mock.Call
}

// GetYearlyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadStore_Expecter) GetYearlyHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadStore_GetYearlyHistory_Call {
	return &MockReadStore_GetYearlyHistory_Call{Call: _e.mock.On("GetYearlyHistory", ctx, key, start, end)}
}

func (_c *MockReadStore_GetYearlyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadStore_GetYearlyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadStore_GetYearlyHistory_Call) Return(_a0 []*history.YearlyDataPoint, _a1 error) *MockReadStore_GetYearlyHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadStore_GetYearlyHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.YearlyDataPoint, error)) *MockReadStore_GetYearlyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadStore creates a new instance of MockReadStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadStore {
	mock := &MockReadStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
