// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/period"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackfillTx creates a new instance of MockBackfillTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackfillTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackfillTx {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBackfillTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBackfillTx is an autogenerated mock type for the BackfillTx type
type MockBackfillTx struct {
	mock.Mock
}

type MockBackfillTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackfillTx) EXPECT() *MockBackfillTx_Expecter {
	return &MockBackfillTx_Expecter{mock: &_m.Mock}
}

// Baseline provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) Baseline() (string, map[string]float64) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Baseline")
	}

	var r0 string
	var r1 map[string]float64
	if returnFunc, ok := ret.Get(0).(func() (string, map[string]float64)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() map[string]float64); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]float64)
		}
	}
	return r0, r1
}

// MockBackfillTx_Baseline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Baseline'
type MockBackfillTx_Baseline_Call struct {
	*mock.Call
}

// Baseline is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) Baseline() *MockBackfillTx_Baseline_Call {
	return &MockBackfillTx_Baseline_Call{Call: _e.mock.On("Baseline")}
}

func (_c *MockBackfillTx_Baseline_Call) Run(run func()) *MockBackfillTx_Baseline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_Baseline_Call) Return(s string, stringToFloat64 map[string]float64) *MockBackfillTx_Baseline_Call {
	_c.Call.Return(s, stringToFloat64)
	return _c
}

func (_c *MockBackfillTx_Baseline_Call) RunAndReturn(run func() (string, map[string]float64)) *MockBackfillTx_Baseline_Call {
	_c.Call.Return(run)
	return _c
}

// Cutover provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) Cutover() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cutover")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBackfillTx_Cutover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cutover'
type MockBackfillTx_Cutover_Call struct {
	*mock.Call
}

// Cutover is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) Cutover() *MockBackfillTx_Cutover_Call {
	return &MockBackfillTx_Cutover_Call{Call: _e.mock.On("Cutover")}
}

func (_c *MockBackfillTx_Cutover_Call) Run(run func()) *MockBackfillTx_Cutover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_Cutover_Call) Return(s string) *MockBackfillTx_Cutover_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBackfillTx_Cutover_Call) RunAndReturn(run func() string) *MockBackfillTx_Cutover_Call {
	_c.Call.Return(run)
	return _c
}

// FirstDailyDay provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) FirstDailyDay() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FirstDailyDay")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackfillTx_FirstDailyDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstDailyDay'
type MockBackfillTx_FirstDailyDay_Call struct {
	*mock.Call
}

// FirstDailyDay is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) FirstDailyDay() *MockBackfillTx_FirstDailyDay_Call {
	return &MockBackfillTx_FirstDailyDay_Call{Call: _e.mock.On("FirstDailyDay")}
}

func (_c *MockBackfillTx_FirstDailyDay_Call) Run(run func()) *MockBackfillTx_FirstDailyDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_FirstDailyDay_Call) Return(s string, err error) *MockBackfillTx_FirstDailyDay_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBackfillTx_FirstDailyDay_Call) RunAndReturn(run func() (string, error)) *MockBackfillTx_FirstDailyDay_Call {
	_c.Call.Return(run)
	return _c
}

// PeriodValue provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) PeriodValue(l period.Level, key string, p string) (float64, bool, error) {
	ret := _mock.Called(l, key, p)

	if len(ret) == 0 {
		panic("no return value specified for PeriodValue")
	}

	var r0 float64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(period.Level, string, string) (float64, bool, error)); ok {
		return returnFunc(l, key, p)
	}
	if returnFunc, ok := ret.Get(0).(func(period.Level, string, string) float64); ok {
		r0 = returnFunc(l, key, p)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(period.Level, string, string) bool); ok {
		r1 = returnFunc(l, key, p)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(period.Level, string, string) error); ok {
		r2 = returnFunc(l, key, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBackfillTx_PeriodValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeriodValue'
type MockBackfillTx_PeriodValue_Call struct {
	*mock.Call
}

// PeriodValue is a helper method to define mock.On call
//   - l period.Level
//   - key string
//   - p string
func (_e *MockBackfillTx_Expecter) PeriodValue(l any, key any, p any) *MockBackfillTx_PeriodValue_Call {
	return &MockBackfillTx_PeriodValue_Call{Call: _e.mock.On("PeriodValue", l, key, p)}
}

func (_c *MockBackfillTx_PeriodValue_Call) Run(run func(l period.Level, key string, p string)) *MockBackfillTx_PeriodValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 period.Level
		if args[0] != nil {
			arg0 = args[0].(period.Level)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackfillTx_PeriodValue_Call) Return(f float64, b bool, err error) *MockBackfillTx_PeriodValue_Call {
	_c.Call.Return(f, b, err)
	return _c
}

func (_c *MockBackfillTx_PeriodValue_Call) RunAndReturn(run func(l period.Level, key string, p string) (float64, bool, error)) *MockBackfillTx_PeriodValue_Call {
	_c.Call.Return(run)
	return _c
}

// PurgedBefore provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) PurgedBefore() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PurgedBefore")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBackfillTx_PurgedBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgedBefore'
type MockBackfillTx_PurgedBefore_Call struct {
	*mock.Call
}

// PurgedBefore is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) PurgedBefore() *MockBackfillTx_PurgedBefore_Call {
	return &MockBackfillTx_PurgedBefore_Call{Call: _e.mock.On("PurgedBefore")}
}

func (_c *MockBackfillTx_PurgedBefore_Call) Run(run func()) *MockBackfillTx_PurgedBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_PurgedBefore_Call) Return(s string) *MockBackfillTx_PurgedBefore_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBackfillTx_PurgedBefore_Call) RunAndReturn(run func() string) *MockBackfillTx_PurgedBefore_Call {
	_c.Call.Return(run)
	return _c
}

// PutBaseline provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) PutBaseline(values map[string]float64) error {
	ret := _mock.Called(values)

	if len(ret) == 0 {
		panic("no return value specified for PutBaseline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]float64) error); ok {
		r0 = returnFunc(values)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackfillTx_PutBaseline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBaseline'
type MockBackfillTx_PutBaseline_Call struct {
	*mock.Call
}

// PutBaseline is a helper method to define mock.On call
//   - values map[string]float64
func (_e *MockBackfillTx_Expecter) PutBaseline(values any) *MockBackfillTx_PutBaseline_Call {
	return &MockBackfillTx_PutBaseline_Call{Call: _e.mock.On("PutBaseline", values)}
}

func (_c *MockBackfillTx_PutBaseline_Call) Run(run func(values map[string]float64)) *MockBackfillTx_PutBaseline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]float64
		if args[0] != nil {
			arg0 = args[0].(map[string]float64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackfillTx_PutBaseline_Call) Return(err error) *MockBackfillTx_PutBaseline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackfillTx_PutBaseline_Call) RunAndReturn(run func(values map[string]float64) error) *MockBackfillTx_PutBaseline_Call {
	_c.Call.Return(run)
	return _c
}

// PutPeriod provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) PutPeriod(l period.Level, key string, p string, v float64) error {
	ret := _mock.Called(l, key, p, v)

	if len(ret) == 0 {
		panic("no return value specified for PutPeriod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(period.Level, string, string, float64) error); ok {
		r0 = returnFunc(l, key, p, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackfillTx_PutPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPeriod'
type MockBackfillTx_PutPeriod_Call struct {
	*mock.Call
}

// PutPeriod is a helper method to define mock.On call
//   - l period.Level
//   - key string
//   - p string
//   - v float64
func (_e *MockBackfillTx_Expecter) PutPeriod(l any, key any, p any, v any) *MockBackfillTx_PutPeriod_Call {
	return &MockBackfillTx_PutPeriod_Call{Call: _e.mock.On("PutPeriod", l, key, p, v)}
}

func (_c *MockBackfillTx_PutPeriod_Call) Run(run func(l period.Level, key string, p string, v float64)) *MockBackfillTx_PutPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 period.Level
		if args[0] != nil {
			arg0 = args[0].(period.Level)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackfillTx_PutPeriod_Call) Return(err error) *MockBackfillTx_PutPeriod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackfillTx_PutPeriod_Call) RunAndReturn(run func(l period.Level, key string, p string, v float64) error) *MockBackfillTx_PutPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// SumDaily provides a mock function for the type MockBackfillTx
func (_mock *MockBackfillTx) SumDaily(key string, from string, to string) (float64, error) {
	ret := _mock.Called(key, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumDaily")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (float64, error)); ok {
		return returnFunc(key, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) float64); ok {
		r0 = returnFunc(key, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(key, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackfillTx_SumDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumDaily'
type MockBackfillTx_SumDaily_Call struct {
	*mock.Call
}

// SumDaily is a helper method to define mock.On call
//   - key string
//   - from string
//   - to string
func (_e *MockBackfillTx_Expecter) SumDaily(key any, from any, to any) *MockBackfillTx_SumDaily_Call {
	return &MockBackfillTx_SumDaily_Call{Call: _e.mock.On("SumDaily", key, from, to)}
}

func (_c *MockBackfillTx_SumDaily_Call) Run(run func(key string, from string, to string)) *MockBackfillTx_SumDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackfillTx_SumDaily_Call) Return(f float64, err error) *MockBackfillTx_SumDaily_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockBackfillTx_SumDaily_Call) RunAndReturn(run func(key string, from string, to string) (float64, error)) *MockBackfillTx_SumDaily_Call {
	_c.Call.Return(run)
	return _c
}
