// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dombyte/solis/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAggregatorStore creates a new instance of MockAggregatorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregatorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregatorStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAggregatorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAggregatorStore is an autogenerated mock type for the AggregatorStore type
type MockAggregatorStore struct {
	mock.Mock
}

type MockAggregatorStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregatorStore) EXPECT() *MockAggregatorStore_Expecter {
	return &MockAggregatorStore_Expecter{mock: &_m.Mock}
}

// CloseState provides a mock function for the type MockAggregatorStore
func (_mock *MockAggregatorStore) CloseState(ctx context.Context) (storage.CloseState, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CloseState")
	}

	var r0 storage.CloseState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (storage.CloseState, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) storage.CloseState); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(storage.CloseState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAggregatorStore_CloseState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseState'
type MockAggregatorStore_CloseState_Call struct {
	*mock.Call
}

// CloseState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAggregatorStore_Expecter) CloseState(ctx any) *MockAggregatorStore_CloseState_Call {
	return &MockAggregatorStore_CloseState_Call{Call: _e.mock.On("CloseState", ctx)}
}

func (_c *MockAggregatorStore_CloseState_Call) Run(run func(ctx context.Context)) *MockAggregatorStore_CloseState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAggregatorStore_CloseState_Call) Return(closeState storage.CloseState, err error) *MockAggregatorStore_CloseState_Call {
	_c.Call.Return(closeState, err)
	return _c
}

func (_c *MockAggregatorStore_CloseState_Call) RunAndReturn(run func(ctx context.Context) (storage.CloseState, error)) *MockAggregatorStore_CloseState_Call {
	_c.Call.Return(run)
	return _c
}

// HasDailyData provides a mock function for the type MockAggregatorStore
func (_mock *MockAggregatorStore) HasDailyData(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HasDailyData")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAggregatorStore_HasDailyData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasDailyData'
type MockAggregatorStore_HasDailyData_Call struct {
	*mock.Call
}

// HasDailyData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAggregatorStore_Expecter) HasDailyData(ctx any) *MockAggregatorStore_HasDailyData_Call {
	return &MockAggregatorStore_HasDailyData_Call{Call: _e.mock.On("HasDailyData", ctx)}
}

func (_c *MockAggregatorStore_HasDailyData_Call) Run(run func(ctx context.Context)) *MockAggregatorStore_HasDailyData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAggregatorStore_HasDailyData_Call) Return(b bool, err error) *MockAggregatorStore_HasDailyData_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAggregatorStore_HasDailyData_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockAggregatorStore_HasDailyData_Call {
	_c.Call.Return(run)
	return _c
}

// SumDaily provides a mock function for the type MockAggregatorStore
func (_mock *MockAggregatorStore) SumDaily(ctx context.Context, key string, from string, to string) (float64, error) {
	ret := _mock.Called(ctx, key, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumDaily")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (float64, error)); ok {
		return returnFunc(ctx, key, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) float64); ok {
		r0 = returnFunc(ctx, key, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, key, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAggregatorStore_SumDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumDaily'
type MockAggregatorStore_SumDaily_Call struct {
	*mock.Call
}

// SumDaily is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - from string
//   - to string
func (_e *MockAggregatorStore_Expecter) SumDaily(ctx any, key any, from any, to any) *MockAggregatorStore_SumDaily_Call {
	return &MockAggregatorStore_SumDaily_Call{Call: _e.mock.On("SumDaily", ctx, key, from, to)}
}

func (_c *MockAggregatorStore_SumDaily_Call) Run(run func(ctx context.Context, key string, from string, to string)) *MockAggregatorStore_SumDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAggregatorStore_SumDaily_Call) Return(f float64, err error) *MockAggregatorStore_SumDaily_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockAggregatorStore_SumDaily_Call) RunAndReturn(run func(ctx context.Context, key string, from string, to string) (float64, error)) *MockAggregatorStore_SumDaily_Call {
	_c.Call.Return(run)
	return _c
}

// WriteComputed provides a mock function for the type MockAggregatorStore
func (_mock *MockAggregatorStore) WriteComputed(ctx context.Context, w storage.ComputedWrite) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for WriteComputed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ComputedWrite) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAggregatorStore_WriteComputed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteComputed'
type MockAggregatorStore_WriteComputed_Call struct {
	*mock.Call
}

// WriteComputed is a helper method to define mock.On call
//   - ctx context.Context
//   - w storage.ComputedWrite
func (_e *MockAggregatorStore_Expecter) WriteComputed(ctx any, w any) *MockAggregatorStore_WriteComputed_Call {
	return &MockAggregatorStore_WriteComputed_Call{Call: _e.mock.On("WriteComputed", ctx, w)}
}

func (_c *MockAggregatorStore_WriteComputed_Call) Run(run func(ctx context.Context, w storage.ComputedWrite)) *MockAggregatorStore_WriteComputed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ComputedWrite
		if args[1] != nil {
			arg1 = args[1].(storage.ComputedWrite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAggregatorStore_WriteComputed_Call) Return(err error) *MockAggregatorStore_WriteComputed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAggregatorStore_WriteComputed_Call) RunAndReturn(run func(ctx context.Context, w storage.ComputedWrite) error) *MockAggregatorStore_WriteComputed_Call {
	_c.Call.Return(run)
	return _c
}
