// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	period "github.com/dombyte/solis/internal/period"
	mock "github.com/stretchr/testify/mock"
)

// MockBackfillTx is an autogenerated mock type for the BackfillTx type
type MockBackfillTx struct {
	mock.Mock
}

type MockBackfillTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackfillTx) EXPECT() *MockBackfillTx_Expecter {
	return &MockBackfillTx_Expecter{mock: &_m.Mock}
}

// Baseline provides a mock function with no fields
func (_m *MockBackfillTx) Baseline() (string, map[string]float64) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Baseline")
	}

	var r0 string
	var r1 map[string]float64
	if rf, ok := ret.Get(0).(func() (string, map[string]float64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() map[string]float64); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]float64)
		}
	}

	return r0, r1
}

// MockBackfillTx_Baseline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Baseline'
type MockBackfillTx_Baseline_Call struct {
	*mock.Call
}

// Baseline is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) Baseline() *MockBackfillTx_Baseline_Call {
	return &MockBackfillTx_Baseline_Call{Call: _e.mock.On("Baseline")}
}

func (_c *MockBackfillTx_Baseline_Call) Run(run func()) *MockBackfillTx_Baseline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_Baseline_Call) Return(_a0 string, _a1 map[string]float64) *MockBackfillTx_Baseline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackfillTx_Baseline_Call) RunAndReturn(run func() (string, map[string]float64)) *MockBackfillTx_Baseline_Call {
	_c.Call.Return(run)
	return _c
}

// Cutover provides a mock function with no fields
func (_m *MockBackfillTx) Cutover() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cutover")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBackfillTx_Cutover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cutover'
type MockBackfillTx_Cutover_Call struct {
	*mock.Call
}

// Cutover is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) Cutover() *MockBackfillTx_Cutover_Call {
	return &MockBackfillTx_Cutover_Call{Call: _e.mock.On("Cutover")}
}

func (_c *MockBackfillTx_Cutover_Call) Run(run func()) *MockBackfillTx_Cutover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_Cutover_Call) Return(_a0 string) *MockBackfillTx_Cutover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackfillTx_Cutover_Call) RunAndReturn(run func() string) *MockBackfillTx_Cutover_Call {
	_c.Call.Return(run)
	return _c
}

// FirstDailyDay provides a mock function with no fields
func (_m *MockBackfillTx) FirstDailyDay() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FirstDailyDay")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackfillTx_FirstDailyDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstDailyDay'
type MockBackfillTx_FirstDailyDay_Call struct {
	*mock.Call
}

// FirstDailyDay is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) FirstDailyDay() *MockBackfillTx_FirstDailyDay_Call {
	return &MockBackfillTx_FirstDailyDay_Call{Call: _e.mock.On("FirstDailyDay")}
}

func (_c *MockBackfillTx_FirstDailyDay_Call) Run(run func()) *MockBackfillTx_FirstDailyDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_FirstDailyDay_Call) Return(_a0 string, _a1 error) *MockBackfillTx_FirstDailyDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackfillTx_FirstDailyDay_Call) RunAndReturn(run func() (string, error)) *MockBackfillTx_FirstDailyDay_Call {
	_c.Call.Return(run)
	return _c
}

// PeriodValue provides a mock function with given fields: l, key, p
func (_m *MockBackfillTx) PeriodValue(l period.Level, key string, p string) (float64, bool, error) {
	ret := _m.Called(l, key, p)

	if len(ret) == 0 {
		panic("no return value specified for PeriodValue")
	}

	var r0 float64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(period.Level, string, string) (float64, bool, error)); ok {
		return rf(l, key, p)
	}
	if rf, ok := ret.Get(0).(func(period.Level, string, string) float64); ok {
		r0 = rf(l, key, p)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(period.Level, string, string) bool); ok {
		r1 = rf(l, key, p)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(period.Level, string, string) error); ok {
		r2 = rf(l, key, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBackfillTx_PeriodValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeriodValue'
type MockBackfillTx_PeriodValue_Call struct {
	*mock.Call
}

// PeriodValue is a helper method to define mock.On call
//   - l period.Level
//   - key string
//   - p string
func (_e *MockBackfillTx_Expecter) PeriodValue(l interface{}, key interface{}, p interface{}) *MockBackfillTx_PeriodValue_Call {
	return &MockBackfillTx_PeriodValue_Call{Call: _e.mock.On("PeriodValue", l, key, p)}
}

func (_c *MockBackfillTx_PeriodValue_Call) Run(run func(l period.Level, key string, p string)) *MockBackfillTx_PeriodValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(period.Level), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBackfillTx_PeriodValue_Call) Return(_a0 float64, _a1 bool, _a2 error) *MockBackfillTx_PeriodValue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBackfillTx_PeriodValue_Call) RunAndReturn(run func(period.Level, string, string) (float64, bool, error)) *MockBackfillTx_PeriodValue_Call {
	_c.Call.Return(run)
	return _c
}

// PurgedBefore provides a mock function with no fields
func (_m *MockBackfillTx) PurgedBefore() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PurgedBefore")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBackfillTx_PurgedBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgedBefore'
type MockBackfillTx_PurgedBefore_Call struct {
	*mock.Call
}

// PurgedBefore is a helper method to define mock.On call
func (_e *MockBackfillTx_Expecter) PurgedBefore() *MockBackfillTx_PurgedBefore_Call {
	return &MockBackfillTx_PurgedBefore_Call{Call: _e.mock.On("PurgedBefore")}
}

func (_c *MockBackfillTx_PurgedBefore_Call) Run(run func()) *MockBackfillTx_PurgedBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackfillTx_PurgedBefore_Call) Return(_a0 string) *MockBackfillTx_PurgedBefore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackfillTx_PurgedBefore_Call) RunAndReturn(run func() string) *MockBackfillTx_PurgedBefore_Call {
	_c.Call.Return(run)
	return _c
}

// PutBaseline provides a mock function with given fields: values
func (_m *MockBackfillTx) PutBaseline(values map[string]float64) error {
	ret := _m.Called(values)

	if len(ret) == 0 {
		panic("no return value specified for PutBaseline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]float64) error); ok {
		r0 = rf(values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackfillTx_PutBaseline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBaseline'
type MockBackfillTx_PutBaseline_Call struct {
	*mock.Call
}

// PutBaseline is a helper method to define mock.On call
//   - values map[string]float64
func (_e *MockBackfillTx_Expecter) PutBaseline(values interface{}) *MockBackfillTx_PutBaseline_Call {
	return &MockBackfillTx_PutBaseline_Call{Call: _e.mock.On("PutBaseline", values)}
}

func (_c *MockBackfillTx_PutBaseline_Call) Run(run func(values map[string]float64)) *MockBackfillTx_PutBaseline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]float64))
	})
	return _c
}

func (_c *MockBackfillTx_PutBaseline_Call) Return(_a0 error) *MockBackfillTx_PutBaseline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackfillTx_PutBaseline_Call) RunAndReturn(run func(map[string]float64) error) *MockBackfillTx_PutBaseline_Call {
	_c.Call.Return(run)
	return _c
}

// PutPeriod provides a mock function with given fields: l, key, p, v
func (_m *MockBackfillTx) PutPeriod(l period.Level, key string, p string, v float64) error {
	ret := _m.Called(l, key, p, v)

	if len(ret) == 0 {
		panic("no return value specified for PutPeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(period.Level, string, string, float64) error); ok {
		r0 = rf(l, key, p, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackfillTx_PutPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPeriod'
type MockBackfillTx_PutPeriod_Call struct {
	*mock.Call
}

// PutPeriod is a helper method to define mock.On call
//   - l period.Level
//   - key string
//   - p string
//   - v float64
func (_e *MockBackfillTx_Expecter) PutPeriod(l interface{}, key interface{}, p interface{}, v interface{}) *MockBackfillTx_PutPeriod_Call {
	return &MockBackfillTx_PutPeriod_Call{Call: _e.mock.On("PutPeriod", l, key, p, v)}
}

func (_c *MockBackfillTx_PutPeriod_Call) Run(run func(l period.Level, key string, p string, v float64)) *MockBackfillTx_PutPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(period.Level), args[1].(string), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *MockBackfillTx_PutPeriod_Call) Return(_a0 error) *MockBackfillTx_PutPeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackfillTx_PutPeriod_Call) RunAndReturn(run func(period.Level, string, string, float64) error) *MockBackfillTx_PutPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// SumDaily provides a mock function with given fields: key, from, to
func (_m *MockBackfillTx) SumDaily(key string, from string, to string) (float64, error) {
	ret := _m.Called(key, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumDaily")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (float64, error)); ok {
		return rf(key, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) float64); ok {
		r0 = rf(key, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(key, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackfillTx_SumDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumDaily'
type MockBackfillTx_SumDaily_Call struct {
	*mock.Call
}

// SumDaily is a helper method to define mock.On call
//   - key string
//   - from string
//   - to string
func (_e *MockBackfillTx_Expecter) SumDaily(key interface{}, from interface{}, to interface{}) *MockBackfillTx_SumDaily_Call {
	return &MockBackfillTx_SumDaily_Call{Call: _e.mock.On("SumDaily", key, from, to)}
}

func (_c *MockBackfillTx_SumDaily_Call) Run(run func(key string, from string, to string)) *MockBackfillTx_SumDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBackfillTx_SumDaily_Call) Return(_a0 float64, _a1 error) *MockBackfillTx_SumDaily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackfillTx_SumDaily_Call) RunAndReturn(run func(string, string, string) (float64, error)) *MockBackfillTx_SumDaily_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackfillTx creates a new instance of MockBackfillTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackfillTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackfillTx {
	mock := &MockBackfillTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
