// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dombyte/solis/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPollerStore creates a new instance of MockPollerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPollerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPollerStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPollerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPollerStore is an autogenerated mock type for the PollerStore type
type MockPollerStore struct {
	mock.Mock
}

type MockPollerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPollerStore) EXPECT() *MockPollerStore_Expecter {
	return &MockPollerStore_Expecter{mock: &_m.Mock}
}

// Seed provides a mock function for the type MockPollerStore
func (_mock *MockPollerStore) Seed(ctx context.Context, days []string) (storage.Seed, error) {
	ret := _mock.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for Seed")
	}

	var r0 storage.Seed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (storage.Seed, error)); ok {
		return returnFunc(ctx, days)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) storage.Seed); ok {
		r0 = returnFunc(ctx, days)
	} else {
		r0 = ret.Get(0).(storage.Seed)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, days)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPollerStore_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type MockPollerStore_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
//   - ctx context.Context
//   - days []string
func (_e *MockPollerStore_Expecter) Seed(ctx any, days any) *MockPollerStore_Seed_Call {
	return &MockPollerStore_Seed_Call{Call: _e.mock.On("Seed", ctx, days)}
}

func (_c *MockPollerStore_Seed_Call) Run(run func(ctx context.Context, days []string)) *MockPollerStore_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPollerStore_Seed_Call) Return(seed storage.Seed, err error) *MockPollerStore_Seed_Call {
	_c.Call.Return(seed, err)
	return _c
}

func (_c *MockPollerStore_Seed_Call) RunAndReturn(run func(ctx context.Context, days []string) (storage.Seed, error)) *MockPollerStore_Seed_Call {
	_c.Call.Return(run)
	return _c
}

// WritePoll provides a mock function for the type MockPollerStore
func (_mock *MockPollerStore) WritePoll(ctx context.Context, w storage.PollWrite) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for WritePoll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.PollWrite) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPollerStore_WritePoll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WritePoll'
type MockPollerStore_WritePoll_Call struct {
	*mock.Call
}

// WritePoll is a helper method to define mock.On call
//   - ctx context.Context
//   - w storage.PollWrite
func (_e *MockPollerStore_Expecter) WritePoll(ctx any, w any) *MockPollerStore_WritePoll_Call {
	return &MockPollerStore_WritePoll_Call{Call: _e.mock.On("WritePoll", ctx, w)}
}

func (_c *MockPollerStore_WritePoll_Call) Run(run func(ctx context.Context, w storage.PollWrite)) *MockPollerStore_WritePoll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.PollWrite
		if args[1] != nil {
			arg1 = args[1].(storage.PollWrite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPollerStore_WritePoll_Call) Return(err error) *MockPollerStore_WritePoll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPollerStore_WritePoll_Call) RunAndReturn(run func(ctx context.Context, w storage.PollWrite) error) *MockPollerStore_WritePoll_Call {
	_c.Call.Return(run)
	return _c
}
