// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	health "github.com/dombyte/solis/internal/health"

	history "github.com/dombyte/solis/internal/history"

	mock "github.com/stretchr/testify/mock"

	service "github.com/dombyte/solis/internal/service"

	solis "github.com/dombyte/solis/internal/solis"

	time "time"
)

// MockReadService is an autogenerated mock type for the ReadService type
type MockReadService struct {
	mock.Mock
}

type MockReadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadService) EXPECT() *MockReadService_Expecter {
	return &MockReadService_Expecter{mock: &_m.Mock}
}

// Current provides a mock function with given fields: key
func (_m *MockReadService) Current(key string) (*solis.Value, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 *solis.Value
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*solis.Value, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *solis.Value); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*solis.Value)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockReadService_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - key string
func (_e *MockReadService_Expecter) Current(key interface{}) *MockReadService_Current_Call {
	return &MockReadService_Current_Call{Call: _e.mock.On("Current", key)}
}

func (_c *MockReadService_Current_Call) Run(run func(key string)) *MockReadService_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockReadService_Current_Call) Return(_a0 *solis.Value, _a1 error) *MockReadService_Current_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_Current_Call) RunAndReturn(run func(string) (*solis.Value, error)) *MockReadService_Current_Call {
	_c.Call.Return(run)
	return _c
}

// DailyHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadService) DailyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.DailyDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for DailyHistory")
	}

	var r0 []*history.DailyDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.DailyDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.DailyDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.DailyDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_DailyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DailyHistory'
type MockReadService_DailyHistory_Call struct {
	*mock.Call
}

// DailyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadService_Expecter) DailyHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadService_DailyHistory_Call {
	return &MockReadService_DailyHistory_Call{Call: _e.mock.On("DailyHistory", ctx, key, start, end)}
}

func (_c *MockReadService_DailyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadService_DailyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadService_DailyHistory_Call) Return(_a0 []*history.DailyDataPoint, _a1 error) *MockReadService_DailyHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_DailyHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.DailyDataPoint, error)) *MockReadService_DailyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with no fields
func (_m *MockReadService) Health() health.Snapshot {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 health.Snapshot
	if rf, ok := ret.Get(0).(func() health.Snapshot); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(health.Snapshot)
	}

	return r0
}

// MockReadService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockReadService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockReadService_Expecter) Health() *MockReadService_Health_Call {
	return &MockReadService_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockReadService_Health_Call) Run(run func()) *MockReadService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadService_Health_Call) Return(_a0 health.Snapshot) *MockReadService_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReadService_Health_Call) RunAndReturn(run func() health.Snapshot) *MockReadService_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function with no fields
func (_m *MockReadService) Keys() []solis.Register {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []solis.Register
	if rf, ok := ret.Get(0).(func() []solis.Register); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solis.Register)
		}
	}

	return r0
}

// MockReadService_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockReadService_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockReadService_Expecter) Keys() *MockReadService_Keys_Call {
	return &MockReadService_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockReadService_Keys_Call) Run(run func()) *MockReadService_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadService_Keys_Call) Return(_a0 []solis.Register) *MockReadService_Keys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReadService_Keys_Call) RunAndReturn(run func() []solis.Register) *MockReadService_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// MonthlyHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadService) MonthlyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.MonthlyDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for MonthlyHistory")
	}

	var r0 []*history.MonthlyDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.MonthlyDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.MonthlyDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.MonthlyDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_MonthlyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonthlyHistory'
type MockReadService_MonthlyHistory_Call struct {
	*mock.Call
}

// MonthlyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadService_Expecter) MonthlyHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadService_MonthlyHistory_Call {
	return &MockReadService_MonthlyHistory_Call{Call: _e.mock.On("MonthlyHistory", ctx, key, start, end)}
}

func (_c *MockReadService_MonthlyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadService_MonthlyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadService_MonthlyHistory_Call) Return(_a0 []*history.MonthlyDataPoint, _a1 error) *MockReadService_MonthlyHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_MonthlyHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.MonthlyDataPoint, error)) *MockReadService_MonthlyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: key
func (_m *MockReadService) Register(key string) (solis.Register, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 solis.Register
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (solis.Register, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) solis.Register); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(solis.Register)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockReadService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - key string
func (_e *MockReadService_Expecter) Register(key interface{}) *MockReadService_Register_Call {
	return &MockReadService_Register_Call{Call: _e.mock.On("Register", key)}
}

func (_c *MockReadService_Register_Call) Run(run func(key string)) *MockReadService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockReadService_Register_Call) Return(_a0 solis.Register, _a1 error) *MockReadService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_Register_Call) RunAndReturn(run func(string) (solis.Register, error)) *MockReadService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// StatusHistory provides a mock function with given fields: ctx, key
func (_m *MockReadService) StatusHistory(ctx context.Context, key string) (service.StatusHistory, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for StatusHistory")
	}

	var r0 service.StatusHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (service.StatusHistory, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) service.StatusHistory); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(service.StatusHistory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_StatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusHistory'
type MockReadService_StatusHistory_Call struct {
	*mock.Call
}

// StatusHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReadService_Expecter) StatusHistory(ctx interface{}, key interface{}) *MockReadService_StatusHistory_Call {
	return &MockReadService_StatusHistory_Call{Call: _e.mock.On("StatusHistory", ctx, key)}
}

func (_c *MockReadService_StatusHistory_Call) Run(run func(ctx context.Context, key string)) *MockReadService_StatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReadService_StatusHistory_Call) Return(_a0 service.StatusHistory, _a1 error) *MockReadService_StatusHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_StatusHistory_Call) RunAndReturn(run func(context.Context, string) (service.StatusHistory, error)) *MockReadService_StatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Total provides a mock function with given fields: ctx, key
func (_m *MockReadService) Total(ctx context.Context, key string) (*history.TotalDataPoint, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Total")
	}

	var r0 *history.TotalDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*history.TotalDataPoint, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *history.TotalDataPoint); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.TotalDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_Total_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Total'
type MockReadService_Total_Call struct {
	*mock.Call
}

// Total is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReadService_Expecter) Total(ctx interface{}, key interface{}) *MockReadService_Total_Call {
	return &MockReadService_Total_Call{Call: _e.mock.On("Total", ctx, key)}
}

func (_c *MockReadService_Total_Call) Run(run func(ctx context.Context, key string)) *MockReadService_Total_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReadService_Total_Call) Return(_a0 *history.TotalDataPoint, _a1 error) *MockReadService_Total_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_Total_Call) RunAndReturn(run func(context.Context, string) (*history.TotalDataPoint, error)) *MockReadService_Total_Call {
	_c.Call.Return(run)
	return _c
}

// YearlyHistory provides a mock function with given fields: ctx, key, start, end
func (_m *MockReadService) YearlyHistory(ctx context.Context, key string, start time.Time, end time.Time) ([]*history.YearlyDataPoint, error) {
	ret := _m.Called(ctx, key, start, end)

	if len(ret) == 0 {
		panic("no return value specified for YearlyHistory")
	}

	var r0 []*history.YearlyDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*history.YearlyDataPoint, error)); ok {
		return rf(ctx, key, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*history.YearlyDataPoint); ok {
		r0 = rf(ctx, key, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.YearlyDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, key, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadService_YearlyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'YearlyHistory'
type MockReadService_YearlyHistory_Call struct {
	*mock.Call
}

// YearlyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start time.Time
//   - end time.Time
func (_e *MockReadService_Expecter) YearlyHistory(ctx interface{}, key interface{}, start interface{}, end interface{}) *MockReadService_YearlyHistory_Call {
	return &MockReadService_YearlyHistory_Call{Call: _e.mock.On("YearlyHistory", ctx, key, start, end)}
}

func (_c *MockReadService_YearlyHistory_Call) Run(run func(ctx context.Context, key string, start time.Time, end time.Time)) *MockReadService_YearlyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReadService_YearlyHistory_Call) Return(_a0 []*history.YearlyDataPoint, _a1 error) *MockReadService_YearlyHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadService_YearlyHistory_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*history.YearlyDataPoint, error)) *MockReadService_YearlyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadService creates a new instance of MockReadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadService {
	mock := &MockReadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
