// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	eventbus "github.com/dombyte/solis/internal/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// MockSubscriber is an autogenerated mock type for the Subscriber type
type MockSubscriber struct {
	mock.Mock
}

type MockSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriber) EXPECT() *MockSubscriber_Expecter {
	return &MockSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: name, buf, p
func (_m *MockSubscriber) Subscribe(name string, buf int, p eventbus.Policy) (<-chan eventbus.Event, func(), error) {
	ret := _m.Called(name, buf, p)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan eventbus.Event
	var r1 func()
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, eventbus.Policy) (<-chan eventbus.Event, func(), error)); ok {
		return rf(name, buf, p)
	}
	if rf, ok := ret.Get(0).(func(string, int, eventbus.Policy) <-chan eventbus.Event); ok {
		r0 = rf(name, buf, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan eventbus.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, eventbus.Policy) func()); ok {
		r1 = rf(name, buf, p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	if rf, ok := ret.Get(2).(func(string, int, eventbus.Policy) error); ok {
		r2 = rf(name, buf, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - name string
//   - buf int
//   - p eventbus.Policy
func (_e *MockSubscriber_Expecter) Subscribe(name interface{}, buf interface{}, p interface{}) *MockSubscriber_Subscribe_Call {
	return &MockSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", name, buf, p)}
}

func (_c *MockSubscriber_Subscribe_Call) Run(run func(name string, buf int, p eventbus.Policy)) *MockSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(eventbus.Policy))
	})
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) Return(_a0 <-chan eventbus.Event, _a1 func(), _a2 error) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) RunAndReturn(run func(string, int, eventbus.Policy) (<-chan eventbus.Event, func(), error)) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriber creates a new instance of MockSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriber {
	mock := &MockSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
