// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dombyte/solis/internal/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriber creates a new instance of MockSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriber {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSubscriber is an autogenerated mock type for the Subscriber type
type MockSubscriber struct {
	mock.Mock
}

type MockSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriber) EXPECT() *MockSubscriber_Expecter {
	return &MockSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockSubscriber
func (_mock *MockSubscriber) Subscribe(name string, buf int, p eventbus.Policy) (<-chan eventbus.Event, func(), error) {
	ret := _mock.Called(name, buf, p)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan eventbus.Event
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int, eventbus.Policy) (<-chan eventbus.Event, func(), error)); ok {
		return returnFunc(name, buf, p)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, eventbus.Policy) <-chan eventbus.Event); ok {
		r0 = returnFunc(name, buf, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan eventbus.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, eventbus.Policy) func()); ok {
		r1 = returnFunc(name, buf, p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, int, eventbus.Policy) error); ok {
		r2 = returnFunc(name, buf, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - name string
//   - buf int
//   - p eventbus.Policy
func (_e *MockSubscriber_Expecter) Subscribe(name any, buf any, p any) *MockSubscriber_Subscribe_Call {
	return &MockSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", name, buf, p)}
}

func (_c *MockSubscriber_Subscribe_Call) Run(run func(name string, buf int, p eventbus.Policy)) *MockSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 eventbus.Policy
		if args[2] != nil {
			arg2 = args[2].(eventbus.Policy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) Return(eventCh <-chan eventbus.Event, fn func(), err error) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(eventCh, fn, err)
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) RunAndReturn(run func(name string, buf int, p eventbus.Policy) (<-chan eventbus.Event, func(), error)) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
